// ════════════════════════════════════════════════════════
//  iPAS AI應用規劃師（中級）考試資料
//  科目一 L21 + 科目二 L22
// ════════════════════════════════════════════════════════

const S1_NOTES = [
  {
    title: '1.1　AI 基礎概念與技術發展',
    items: [
      {
        kw: 'AI 定義與分類',
        text: '弱 AI（ANI）解決特定任務；通用 AI（AGI）擁有人類水準智能（尚未實現）；超 AI（ASI）超越人類（理論概念）',
      },
      {
        kw: 'ML / DL / RL 關係',
        text: '機器學習（ML）⊃ 深度學習（DL）；強化學習（RL）屬 ML 的分支，透過獎勵信號學習策略',
      },
      {
        kw: '深度學習核心架構',
        text: '',
        sub: [
          'CNN（卷積神經網路）→ 影像辨識、物件偵測',
          'RNN / LSTM → 序列資料、時間序列預測',
          'Transformer → NLP 翻譯、問答系統（BERT、GPT）',
          'GAN（生成對抗網路）→ 圖像生成、資料擴充',
        ],
      },
      {
        kw: 'NLP 應用',
        text: '情感分析、機器翻譯、文件摘要、命名實體識別（NER）、問答系統、Chatbot',
      },
      {
        kw: '電腦視覺應用',
        text: '影像分類、物件偵測（YOLO、Faster R-CNN）、語意分割、人臉辨識、OCR',
      },
      {
        kw: '多模態 AI',
        text: '同時處理文字＋影像＋音訊等多種輸入，例：GPT-4V、Gemini、DALL-E（文字→圖像）',
      },
      {
        kw: '學習方式分類',
        text: '',
        sub: [
          '監督式學習（Supervised）：有標注 (X, Y)，學習映射關係 → 分類、迴歸',
          '非監督式學習（Unsupervised）：無標注，發現資料結構 → 分群、降維、異常偵測',
          '半監督式學習（Semi-supervised）：少量標注 + 大量無標注資料',
          '自監督學習（Self-supervised）：從資料本身構造監督信號（如 BERT 遮蔽預測）',
          '強化學習（RL）：Agent 與環境互動，透過獎勵信號學習最佳策略',
        ],
      },
      {
        kw: '激活函數',
        text: '',
        sub: [
          'ReLU：f(x) = max(0, x)，最常用，計算快，可能有 Dead Neuron 問題',
          'Sigmoid：f(x) = 1/(1+e^-x)，輸出 [0,1]，二元分類輸出層；有梯度消失問題',
          'Softmax：多分類輸出層，將向量轉為機率分佈（總和=1）',
          'GELU：Transformer 常用，比 ReLU 更平滑',
        ],
      },
      {
        kw: '過擬合（Overfitting）防止方法',
        text: '',
        sub: [
          'Dropout：訓練時隨機丟棄部分神經元，防止依賴特定特徵',
          'L1/L2 正則化：在損失函數加入權重懲罰項',
          'Early Stopping：驗證損失不再下降時停止訓練',
          'Data Augmentation：透過旋轉/翻轉/裁切等增加訓練樣本多樣性',
          'K-Fold 交叉驗證：更可靠地評估泛化能力',
        ],
      },
      {
        kw: 'VAE（變分自編碼器）vs GAN',
        text: '',
        sub: [
          'VAE：編碼器→潛在分佈（μ, σ）→採樣→解碼器；損失 = 重建損失 + KL 散度；生成多樣但略模糊',
          'GAN：生成器 vs 判別器對抗訓練；生成品質高但訓練不穩定（模式崩塌風險）',
          '擴散模型（Diffusion）：逐步加雜訊再學習去雜訊；目前圖像生成 SOTA（Stable Diffusion）',
        ],
      },
      {
        kw: '詞嵌入（Word Embedding）',
        text: '',
        sub: [
          'One-Hot Encoding：稀疏高維向量，無法反映詞義相似性',
          'Word2Vec（Skip-gram/CBOW）：低維稠密向量，語意相近的詞向量距離近',
          'BERT Embedding：上下文相關動態向量，同詞不同語境有不同向量',
        ],
      },
      {
        kw: 'Transformer 架構要點',
        text: '',
        sub: [
          '自注意力（Self-Attention）：每個位置直接關注所有其他位置，解決 RNN 長距離依賴與無法並行問題',
          '多頭注意力（Multi-Head）：多個注意力頭並行，捕捉不同語意面向',
          '位置編碼（Positional Encoding）：因注意力無序列概念，需額外注入位置資訊',
          'BERT：雙向 Encoder，擅長理解（分類/NER/問答）',
          'GPT：單向 Decoder，擅長生成（文字補全/對話）',
        ],
      },
    ],
  },
  {
    title: '1.2　生成式 AI（GenAI）與 LLM',
    items: [
      {
        kw: 'LLM 訓練流程',
        text: 'Pre-training（大規模無標注語料）→ Fine-tuning（特定任務資料）→ RLHF（人類回饋強化學習）',
      },
      {
        kw: 'Prompt Engineering',
        text: '',
        sub: [
          'Zero-shot：無範例直接提問',
          'Few-shot：提供 3~5 個輸入/輸出示範',
          'Chain-of-Thought（CoT）：要求模型逐步推理，提升複雜題目準確度',
          'System Prompt：設定角色與行為準則',
        ],
      },
      {
        kw: 'RAG（檢索增強生成）',
        text: '推論時先從外部知識庫檢索相關文件，再與問題一起送給 LLM，有效降低幻覺並引用最新資料',
      },
      {
        kw: 'Fine-tuning vs RAG',
        text: '',
        sub: [
          'Fine-tuning → 學習特定領域語言風格、術語，需重新訓練',
          'RAG → 無需訓練，即時引用外部文件，適合知識頻繁更新',
        ],
      },
      {
        kw: 'AI 幻覺（Hallucination）',
        text: 'LLM 生成聽起來合理但不正確的資訊，緩解方法：RAG、RLHF、溫度降低、輸出驗證',
      },
      {
        kw: 'AI Agent',
        text: '具備「工具使用（Tool Use）+ 規劃（Planning）+ 動態記憶（Memory）」能力，可自主完成多步驟任務',
      },
      {
        kw: '向量資料庫',
        text: '儲存文字 Embedding 向量，支援語意搜尋（如 Pinecone、Weaviate、pgvector）',
      },
      {
        kw: '常見 GenAI 工具',
        text: 'ChatGPT（OpenAI）、Gemini（Google）、Claude（Anthropic）、Copilot（Microsoft）、Llama（Meta，開源）',
      },
      {
        kw: 'LoRA / PEFT 高效微調',
        text: '',
        sub: [
          'LoRA（Low-Rank Adaptation）：注入低秩矩陣 A×B，可訓練參數減少 99%+',
          'QLoRA：在量化（4-bit）基礎上進行 LoRA，讓消費級 GPU 可微調 70B 模型',
          '適用場景：垂直領域客製化（法律、醫療），比全量微調成本低 10~100 倍',
        ],
      },
      {
        kw: 'LLM 推論參數',
        text: '',
        sub: [
          'Temperature（溫度）：值越低輸出越確定保守，值越高越隨機創意（0=貪婪, 1=正常, >1=隨機）',
          'Top-p（Nucleus Sampling）：從累積機率達 p 的 Token 中採樣，平衡多樣性與品質',
          'Max Tokens：限制輸出長度',
          'Context Window：模型單次可處理的最大 Token 數（輸入+輸出），超過則截斷早期內容',
        ],
      },
      {
        kw: 'LLM 評估指標',
        text: '',
        sub: [
          'BLEU Score：比對機器生成與參考文字的 n-gram 重疊，常用於翻譯評估',
          'ROUGE：以召回率為主，常用於摘要評估（ROUGE-N、ROUGE-L）',
          'Perplexity（困惑度）：衡量語言模型對測試集的預測能力，越低越好',
          '人工評估（Human Eval）：最可靠但成本高，用於最終品質評估',
        ],
      },
      {
        kw: 'AI Agent 架構',
        text: '',
        sub: [
          '工具使用（Tool Use）：呼叫搜尋、計算器、資料庫等外部工具',
          '規劃（Planning）：ReAct（推理+行動交替）、Tree-of-Thought（多路徑推理）',
          '記憶（Memory）：短期（對話歷史）+ 長期（向量資料庫存儲知識）',
          'Multi-Agent：多個 AI Agent 協作分工（如 AutoGen、CrewAI）',
        ],
      },
      {
        kw: 'LLM 安全風險',
        text: '',
        sub: [
          '提示注入（Prompt Injection）：惡意輸入覆蓋系統提示，執行非預期操作',
          '幻覺（Hallucination）：生成聽起來合理但錯誤的內容；緩解：RAG、事實核查',
          '越獄（Jailbreak）：透過技巧繞過安全限制',
          '供應鏈攻擊：公開模型倉庫植入後門（如 Hugging Face 惡意模型）',
        ],
      },
    ],
  },
  {
    title: '1.3　AI 治理、倫理與法規',
    items: [
      {
        kw: 'AI 倫理六大原則',
        text: '公平性（Fairness）、透明性（Transparency）、問責性（Accountability）、可靠性（Reliability）、隱私（Privacy）、包容性（Inclusiveness）',
      },
      {
        kw: '台灣 AI 基本法（2024）',
        text: '強調人本 AI、資安保護、倫理審查，規範政府 AI 應用，確保 AI 可問責與透明',
      },
      {
        kw: 'EU AI Act（2024）',
        text: '全球第一部 AI 綜合法規，按風險分四級：',
        sub: [
          '🚫 不可接受風險（禁止）：社會信用評分、即時大規模生物辨識監控',
          '⚠️ 高風險：醫療、就業、基礎設施、教育，需嚴格合規要求',
          '⚡ 有限風險：需透明度義務（如 Chatbot 須告知使用者是 AI）',
          '✅ 最小風險：大多數 AI 應用，無強制規範（如垃圾郵件過濾）',
        ],
      },
      {
        kw: 'GDPR',
        text: '歐盟通用資料保護法規：規範個人資料蒐集/處理，賦予資料主體「被遺忘權」「資料可攜權」',
      },
      {
        kw: 'AI 偏見（Bias）類型',
        text: '',
        sub: [
          '選擇偏差：訓練資料不代表真實分佈',
          '歷史偏差：資料反映過去社會不公平（如種族、性別歧視）',
          '確認偏差：系統傾向確認已有假設',
        ],
      },
      {
        kw: '可解釋 AI（XAI）',
        text: 'SHAP（量化特徵貢獻度）、LIME（局部線性近似解釋）；滿足法規對模型透明性要求',
      },
      {
        kw: '資料去識別化',
        text: '匿名化（Anonymization）= 不可逆，GDPR 不適用；假名化（Pseudonymization）= 可透過對照表還原，仍受 GDPR 規範',
      },
      {
        kw: 'AI 公平性指標',
        text: '',
        sub: [
          '人口統計均等（Demographic Parity）：不同群體獲得正向預測的比例相同',
          '均等機會（Equal Opportunity）：不同群體的 Recall（真陽性率）相同',
          '校準（Calibration）：預測機率準確反映實際發生機率',
          '公平性不可能定理：多個公平性指標在數學上無法同時完全滿足',
        ],
      },
      {
        kw: '聯邦學習（Federated Learning）',
        text: '資料留在本地，只上傳模型梯度/更新至中央伺服器聚合；保護資料隱私，適合醫療、金融等場景',
      },
      {
        kw: 'GDPR 資料主體權利',
        text: '',
        sub: [
          '知情權（Right to Information）：知道資料如何被使用',
          '存取權（Right of Access）：可要求查看個人資料',
          '更正權（Right to Rectification）：更正不正確資料',
          '被遺忘權（Right to Erasure）：特定條件下要求刪除資料',
          '資料可攜權（Data Portability）：以通用格式取得並移轉個人資料',
        ],
      },
      {
        kw: 'EU AI Act 重點規定',
        text: '',
        sub: [
          '禁止：即時生物辨識、社會信用評分、操控潛意識的 AI',
          '高風險 AI 義務：風險管理、資料治理、透明性、人工監督、準確性/健壯性要求',
          'GPAI（通用 AI）：大型基礎模型有額外透明度與版權義務',
          '違規罰款：最高 3,500 萬歐元或全球營收 7%',
        ],
      },
    ],
  },
  {
    title: '1.4　AI 導入規劃與 MLOps',
    items: [
      {
        kw: 'AI 導入流程',
        text: '問題定義 → 資料蒐集/清洗 → 模型選擇/訓練 → 評估驗證 → 部署 → 監控 → 迭代優化',
      },
      {
        kw: '技術可行性評估',
        text: '資料品質/量、算力需求、技術成熟度、預期效益、導入成本、維護複雜度',
      },
      {
        kw: 'ROI 評估',
        text: '量化指標：效率提升 %、錯誤率降低 %、人力節省；計算預期投資回收期（Payback Period）',
      },
      {
        kw: '風險評估矩陣',
        text: '橫軸：影響程度（Impact）；縱軸：發生機率（Likelihood）；依象限採取接受/監控/緩解/迴避策略',
      },
      {
        kw: 'MLOps',
        text: '將 ML 模型開發、部署、監控自動化的最佳實踐；包含 CI/CD、模型版本控制（MLflow、DVC）、自動重訓練',
      },
      {
        kw: '資料漂移 vs 概念漂移',
        text: '',
        sub: [
          '資料漂移（Data Drift）：輸入特徵 P(X) 分佈改變',
          '概念漂移（Concept Drift）：P(Y|X) 關係改變，即相同輸入的正確答案變了',
        ],
      },
      {
        kw: 'CRISP-DM 標準流程',
        text: '業務理解 → 資料理解 → 資料準備（最耗時）→ 建模 → 評估 → 部署；可迭代回溯，是最廣泛使用的資料探勘方法論',
      },
      {
        kw: 'MLflow 核心功能',
        text: '',
        sub: [
          'Tracking：記錄實驗超參數、評估指標、模型文件、程式碼版本',
          'Projects：可重現的訓練環境打包（conda/docker）',
          'Models：統一模型格式，支援多框架（sklearn、PyTorch、TensorFlow）',
          'Registry：模型版本管理（Staging → Production → Archived 生命週期）',
        ],
      },
      {
        kw: 'DVC（Data Version Control）',
        text: '基於 Git 的資料集與模型版本控制；.dvc 文件記錄指向實際大型文件（S3/GCS）的指標，確保程式碼與資料版本對應，支援實驗重現',
      },
      {
        kw: 'HITL 與主動學習',
        text: '',
        sub: [
          'HITL（Human-in-the-Loop）：在 AI 流程關鍵節點引入人類標注/審核/決策',
          '主動學習（Active Learning）：模型挑選最不確定的樣本請人標注，最小化標注成本',
          'RLHF：收集人類對輸出的偏好排序，訓練獎勵模型引導 LLM',
        ],
      },
      {
        kw: '模型壓縮技術',
        text: '',
        sub: [
          '量化（Quantization）：float32 → int8/float16，記憶體降低 2~4 倍，推論加速',
          '剪枝（Pruning）：移除貢獻低的權重或神經元（結構化/非結構化）',
          '知識蒸餾（Knowledge Distillation）：教師模型的 Soft Label 訓練小型學生模型',
          '應用場景：Edge AI 部署、行動裝置推論、降低推論成本',
        ],
      },
      {
        kw: 'AutoML 與超參數最佳化',
        text: '',
        sub: [
          'Grid Search：窮舉所有組合，適合小搜索空間',
          'Random Search：隨機採樣，比 Grid Search 更有效率',
          'Bayesian Optimization：根據先前結果建立代理模型，智慧選擇下一個評估點（Hyperopt、Optuna）',
          'NAS（Neural Architecture Search）：自動搜索最佳網路架構',
        ],
      },
      {
        kw: 'AI 導入決策框架',
        text: '',
        sub: [
          'Build（自建）：核心競爭力/高客製化需求，成本高時程長',
          'Buy（採購 SaaS）：通用功能，快速上線，資料主控權低',
          'Open Source：彈性高、無授權費，需自行部署維護',
          'PoC（概念驗證）：小規模實驗驗證可行性，通常 2~4 週，成功後再全面導入',
        ],
      },
    ],
  },
  {
    title: '1.5　AI 應用場景',
    items: [
      {
        kw: '製造業',
        text: '預測性維護（感測器時序 → 故障預測）、瑕疵檢測（CNN 影像辨識）、生產排程優化',
      },
      {
        kw: '金融業',
        text: '信用評分（邏輯迴歸/XGBoost）、詐欺偵測（異常偵測）、演算法交易、客服 Chatbot',
      },
      {
        kw: '醫療業',
        text: 'X 光/MRI 影像診斷（CNN）、新藥研發（分子生成）、病歷 NLP 分析、手術輔助機器人',
      },
      {
        kw: '零售業',
        text: '推薦系統（協同過濾/內容過濾）、需求預測（時序模型）、客戶分群（K-means）',
      },
      {
        kw: '推薦系統',
        text: '',
        sub: [
          '協同過濾（CF）：根據相似用戶/商品的歷史行為推薦',
          '內容過濾（Content-based）：根據商品本身特徵比對用戶偏好',
          '混合式：結合兩者優點',
        ],
      },
      {
        kw: 'Edge AI（邊緣 AI）',
        text: '',
        sub: [
          '定義：在本地裝置（手機、IoT、嵌入式）執行 AI 推論，不依賴雲端',
          '優點：低延遲（毫秒級）、離線可用、原始資料不上傳（隱私保護）、降低頻寬成本',
          '挑戰：算力/記憶體受限，需搭配量化、剪枝、蒸餾等模型壓縮技術',
          '應用：智慧監控攝影機、自駕車感知、工廠品質檢測、穿戴裝置健康監測',
        ],
      },
      {
        kw: '電腦視覺詳細應用',
        text: '',
        sub: [
          '影像分類（Image Classification）：ResNet、VGG → 判斷圖像屬於哪個類別',
          '物件偵測（Object Detection）：YOLO、Faster R-CNN → 定位並分類多個物件（Bounding Box）',
          '語意分割（Semantic Segmentation）：FCN → 每個像素分類，不區分個體',
          '實例分割（Instance Segmentation）：Mask R-CNN → 同類物體各自獨立遮罩',
          'OCR（光學字元辨識）：文件數位化、車牌辨識、票據識別',
        ],
      },
      {
        kw: 'NLP 詳細應用',
        text: '',
        sub: [
          '命名實體識別（NER）：從文字中識別人名/地名/組織/日期等實體',
          '情感分析（Sentiment Analysis）：判斷文字正/負/中性情感',
          '機器翻譯（MT）：Seq2Seq + Attention → Transformer（Google Translate）',
          '文件摘要（Summarization）：抽取式（選重要句子）vs 生成式（重新改寫）',
          '問答系統（QA）：開放域 QA（RAG）vs 封閉域 QA（文件理解）',
        ],
      },
      {
        kw: '智慧醫療 AI',
        text: '',
        sub: [
          '醫學影像診斷：X 光、CT、MRI、皮膚鏡影像 → CNN 輔助診斷（需 Grad-CAM 解釋）',
          '藥物研發：分子生成（GAN/Diffusion）、蛋白質結構預測（AlphaFold）',
          '電子病歷（EHR）分析：NLP 提取臨床資訊，預測再入院風險',
          '注意事項：FDA/TFDA 審核、臨床試驗驗證、醫師最終決策（HITL）',
        ],
      },
    ],
  },
];

const S2_NOTES = [
  {
    title: '2.1　大數據基礎概念',
    items: [
      {
        kw: '大數據 5V 特性',
        text: 'Volume（體量大）、Velocity（速度快）、Variety（多樣性高）、Veracity（真實性/準確性）、Value（價值密度低）',
      },
      {
        kw: '資料類型',
        text: '',
        sub: [
          '結構化：關聯式資料庫表格（SQL）',
          '半結構化：JSON、XML、CSV（有格式但不嚴格）',
          '非結構化：圖片、影片、音訊、自然語言文字',
        ],
      },
      {
        kw: '資料倉儲 vs 資料湖 vs 資料湖倉',
        text: '',
        sub: [
          '資料倉儲（DW）：Schema on Write，ETL 後結構化，適合 BI 查詢（Redshift、BigQuery）',
          '資料湖（DL）：Schema on Read，原始格式儲存，適合資料科學探索（S3 + Spark）',
          '資料湖倉（Lakehouse）：結合兩者，支援 ACID 事務（Delta Lake、Apache Iceberg）',
        ],
      },
      {
        kw: '批次處理 vs 串流處理',
        text: '批次（Batch）：定期大量處理歷史資料（如每日報表）；串流（Streaming）：即時連續處理（如詐欺偵測）',
      },
      {
        kw: 'ETL vs ELT',
        text: '',
        sub: [
          'ETL（Extract-Transform-Load）：先轉換後載入，適合傳統資料倉儲，規則固定',
          'ELT（Extract-Load-Transform）：先載入原始資料至雲端倉儲，再利用倉儲算力轉換，更彈性',
          'ELT 是現代資料棧（dbt + BigQuery/Snowflake）的主流模式',
        ],
      },
      {
        kw: '資料格式比較',
        text: '',
        sub: [
          'CSV/JSON：人類可讀，適合小量資料交換，無法壓縮',
          'Parquet：列式儲存，壓縮率高，適合 OLAP 分析查詢（Spark/BigQuery 首選）',
          'Avro：行式二進位格式，支援 Schema 演進，適合 Kafka 訊息序列化',
          'ORC：Hive 最佳化格式，列式壓縮率極高，Hive/Presto 常用',
        ],
      },
      {
        kw: '資料品質六維度',
        text: '',
        sub: [
          '完整性（Completeness）：無缺失值/NULL',
          '準確性（Accuracy）：資料正確無誤',
          '一致性（Consistency）：跨系統相同實體資料一致',
          '時效性（Timeliness）：資料是否最新',
          '唯一性（Uniqueness）：無重複記錄',
          '有效性（Validity）：符合業務規則與格式規範',
        ],
      },
      {
        kw: '資料血緣（Data Lineage）',
        text: '記錄資料從原始來源→ETL轉換→最終報表的完整流向；用於錯誤追溯、GDPR 合規（被遺忘權執行）、影響分析',
      },
    ],
  },
  {
    title: '2.2　Hadoop 生態系統',
    items: [
      {
        kw: 'HDFS 分散式儲存',
        text: '將大檔案切成 Block（預設 128MB），預設複製 3 份存於不同 DataNode（含跨機架）',
      },
      {
        kw: 'NameNode vs DataNode',
        text: 'NameNode：儲存 metadata（目錄結構、Block 位置）—— 是 SPOF 需設 HA；DataNode：儲存實際資料 Block',
      },
      {
        kw: 'MapReduce 運算框架',
        text: '',
        sub: [
          'Map 階段：將輸入資料轉換為 (Key, Value) 對',
          'Shuffle & Sort 階段：相同 Key 的資料歸併到同一 Reducer',
          'Reduce 階段：對每個 Key 的所有 Value 進行聚合計算（如加總、計數）',
        ],
      },
      {
        kw: 'YARN 資源管理',
        text: 'ResourceManager（全域調度）+ NodeManager（節點資源）+ ApplicationMaster（應用程式管理）',
      },
      {
        kw: 'Hive',
        text: '將 HiveQL（類 SQL）轉換為 MapReduce/Tez 執行，適合批次查詢大型資料集',
      },
      {
        kw: 'HBase',
        text: '基於 HDFS 的 NoSQL 列式資料庫，支援隨機讀寫，適合低延遲即時查詢（如用戶資料存取）',
      },
      {
        kw: 'ZooKeeper',
        text: '分散式協調服務：設定管理、分散式鎖、Leader 選舉（Hadoop HA、Kafka 依賴它）',
      },
      {
        kw: 'Hadoop HA 架構',
        text: 'Active/Standby 兩個 NameNode，透過 ZooKeeper 監控，Active 故障時自動 Failover；JournalNode 同步 Editlog，解決 NameNode 單點故障（SPOF）問題',
      },
      {
        kw: 'Hive vs HBase 選擇',
        text: '',
        sub: [
          'Hive：適合批次 SQL 分析（每日報表、歷史資料分析），延遲秒~分鐘級',
          'HBase：適合低延遲隨機讀寫（用戶行為記錄、即時查詢），延遲毫秒級',
          '常見組合：Kafka 收集 → HBase 即時查詢 + Hive 批次分析',
        ],
      },
      {
        kw: 'Apache Sqoop & Flume',
        text: '',
        sub: [
          'Sqoop：RDBMS ↔ HDFS/Hive 批次資料遷移（sqoop import/export），底層用 MapReduce',
          'Flume：分散式日誌收集框架，Source→Channel→Sink 管線，即時擷取 Web 伺服器日誌至 HDFS',
        ],
      },
      {
        kw: '資料倉儲 Schema 設計',
        text: '',
        sub: [
          '星型綱要（Star Schema）：事實表直連非正規化維度表，JOIN 少、查詢快，有資料冗餘',
          '雪花綱要（Snowflake Schema）：維度表進一步正規化，節省空間但 JOIN 多、查詢慢',
          '事實表（Fact Table）：儲存業務事件度量值（銷售金額、點擊次數）',
          '維度表（Dimension Table）：儲存描述性屬性（時間、地區、產品類別）',
        ],
      },
    ],
  },
  {
    title: '2.3　Apache Spark',
    items: [
      {
        kw: 'Spark vs MapReduce',
        text: 'Spark 使用記憶體內（In-Memory）運算，速度比 MapReduce 快 10~100 倍；適合迭代演算法（ML 訓練）',
      },
      {
        kw: 'RDD（彈性分散式資料集）',
        text: '不可變、可分區、支援容錯的分散式資料集；透過 DAG 追蹤血緣（Lineage），節點故障時可重新計算',
      },
      {
        kw: 'Spark 元件',
        text: '',
        sub: [
          'Spark Core：基礎執行引擎與 RDD 操作',
          'Spark SQL：結構化資料查詢（DataFrame API）',
          'Spark Streaming / Structured Streaming：串流資料處理',
          'MLlib：分散式機器學習（如分散式 K-means、線性迴歸）',
          'GraphX：圖計算框架',
        ],
      },
      {
        kw: '惰性求值（Lazy Evaluation）',
        text: 'Transformation（如 map、filter、join）不立即執行；Action（如 count、collect、saveAsTextFile）觸發實際計算',
      },
      {
        kw: 'DAG（有向無環圖）',
        text: 'Spark 將所有 Transformation 建構成 DAG，分析後切割為 Stage 最佳化執行，避免冗餘計算',
      },
      {
        kw: 'Spark 效能最佳化',
        text: '',
        sub: [
          'Cache/Persist：將中間結果快取記憶體，避免迭代計算重複讀取',
          'Broadcast Join：小表廣播至各節點，大表本地 JOIN，避免 Shuffle',
          '分區調整：repartition（增加分區，重新 Shuffle）vs coalesce（減少分區，避免 Shuffle）',
          'Catalyst 最佳化器：自動執行謂詞下推（Predicate Pushdown）、列裁剪（Column Pruning）',
          '資料傾斜（Skew）：加鹽（Salting）技術分散熱點 Key',
        ],
      },
      {
        kw: 'Spark Window Functions',
        text: '在視窗（分區+排序）內計算聚合而不合併行；常用：ROW_NUMBER()、RANK()、LAG/LEAD、滾動平均；適合排行榜、時序分析、用戶行為序列分析',
      },
      {
        kw: 'Structured Streaming',
        text: '以「無限增長的 DataFrame」處理串流資料；Event Time 支援、Watermark 處理遲到事件；Output Modes：Append（只輸出新行）/ Update / Complete',
      },
    ],
  },
  {
    title: '2.4　串流處理與訊息佇列',
    items: [
      {
        kw: 'Apache Kafka',
        text: '高吞吐量分散式訊息佇列；核心概念：Producer → Topic → Partition → Consumer Group',
      },
      {
        kw: 'Kafka Offset',
        text: 'Consumer 記錄在 Partition 中的讀取位置；支援訊息重播（Replay），預設保留 7 天',
      },
      {
        kw: 'Consumer Group',
        text: '同一 Group 內每個 Partition 只由一個 Consumer 消費（保序）；不同 Group 可各自獨立消費全量',
      },
      {
        kw: 'Lambda 架構',
        text: '批次層（全量歷史，高延遲）+ 速度層（最新串流，低延遲）+ 服務層（合併結果）；複雜但完整',
      },
      {
        kw: 'Kappa 架構',
        text: '僅使用串流處理層，去除批次層；架構更簡單，適合可以重播歷史訊息的場景（如 Kafka）',
      },
      {
        kw: '水印（Watermark）',
        text: '定義系統等待遲到事件的最長時間，超過 Watermark 的舊事件不再等待，讓視窗可觸發計算',
      },
      {
        kw: 'Apache Flink',
        text: '低延遲有狀態串流框架，支援 Exactly-Once 語意；可同時做批次和串流（Unified Batch+Stream）',
      },
      {
        kw: 'Kafka 架構詳解',
        text: '',
        sub: [
          'Topic：訊息的邏輯分類；Partition：Topic 的物理分割，是平行度單位',
          'Leader/Follower Replica：每個 Partition 有一個 Leader 負責讀寫，Follower 同步備份',
          'ISR（In-Sync Replicas）：與 Leader 同步的副本集合，資料寫入 ISR 才算提交',
          'Retention Policy：按時間（預設 7 天）或按大小保留訊息，支援歷史重播',
          'Offset 管理：Consumer 提交 Offset 至 __consumer_offsets Topic，重啟後繼續消費',
        ],
      },
      {
        kw: '串流處理語意保證',
        text: '',
        sub: [
          'At-Most-Once（最多一次）：可能遺失，不重試，延遲最低',
          'At-Least-Once（至少一次）：可能重複，適合可冪等操作',
          'Exactly-Once（恰好一次）：最強保證，Flink Checkpoint + Kafka Transactions 實現，成本最高',
        ],
      },
      {
        kw: '串流視窗類型',
        text: '',
        sub: [
          '滾動視窗（Tumbling Window）：固定大小、不重疊，每個事件只屬一個視窗（如每 5 分鐘統計）',
          '滑動視窗（Sliding Window）：固定大小、可重疊，按步長移動（如每分鐘計算過去 5 分鐘）',
          '會話視窗（Session Window）：按活動間隔動態調整，閒置超過閾值則關閉視窗',
        ],
      },
    ],
  },
  {
    title: '2.5　CAP 理論與分散式資料庫',
    items: [
      {
        kw: 'CAP 定理',
        text: '分散式系統無法同時滿足三個特性；P（分區容錯）實務上必須保留，故只能選 CP 或 AP',
        sub: [
          'C（Consistency）一致性：所有節點看到相同最新資料',
          'A（Availability）可用性：每個請求都有回應（不保證最新）',
          'P（Partition Tolerance）分區容錯性：網路分裂時系統仍可運作',
        ],
      },
      {
        kw: 'CP 系統',
        text: '優先保證一致性，網路分區時可能拒絕請求；例：HBase、ZooKeeper、MongoDB（強一致模式）',
      },
      {
        kw: 'AP 系統',
        text: '優先保證可用性，允許最終一致性；例：Cassandra、DynamoDB、CouchDB、Riak',
      },
      {
        kw: 'BASE 理論',
        text: 'Basically Available（基本可用）+ Soft State（軟狀態，中間態）+ Eventually Consistent（最終一致性）',
      },
      {
        kw: '分片（Sharding）vs 副本（Replication）',
        text: '分片：資料水平切割至不同節點，提升寫入量與儲存容量；副本：同一份資料複製多份，提升讀取效能與容錯',
      },
      {
        kw: 'NoSQL 四大類型比較',
        text: '',
        sub: [
          'Key-Value（Redis、DynamoDB）：最簡單，快取/Session/排行榜，O(1) 讀寫',
          'Document（MongoDB、CouchDB）：JSON/BSON 文件，靈活 Schema，適合內容管理、用戶檔案',
          'Column-Family（Cassandra、HBase）：寬列，海量時序/IoT 資料，高寫入吞吐',
          'Graph（Neo4j、Amazon Neptune）：節點+邊，社群網路/知識圖譜/詐欺偵測',
        ],
      },
      {
        kw: 'ACID vs BASE 比較',
        text: '',
        sub: [
          'ACID（傳統 RDBMS）：原子性/一致性/隔離性/持久性，強一致性，適合金融交易',
          'BASE（NoSQL）：基本可用/軟狀態/最終一致性，高可用優先，適合大規模分散式應用',
          '現代趨勢：NewSQL（如 Google Spanner、TiDB）嘗試在分散式環境實現 ACID',
        ],
      },
      {
        kw: '現代開放表格格式',
        text: '',
        sub: [
          'Delta Lake：Parquet + 事務日誌，支援 ACID/Time Travel/Upsert，Databricks 主推',
          'Apache Iceberg：開放標準，Schema Evolution/Hidden Partitioning，Netflix/Apple 廣泛使用',
          'Apache Hudi：Upsert 效能最佳化，適合近即時 CDC（Change Data Capture）場景',
          '三者統稱 Lakehouse 格式，讓資料湖具備資料倉儲的可靠性',
        ],
      },
    ],
  },
  {
    title: '2.6　資料分析與統計',
    items: [
      {
        kw: '特徵縮放',
        text: '',
        sub: [
          'Min-Max Normalization：x\' = (x − min) / (max − min)，縮放至 [0, 1]，對異常值敏感',
          'Z-score Standardization：x\' = (x − μ) / σ，均值 0 標準差 1，對異常值更穩健',
        ],
      },
      {
        kw: 'PCA 主成分分析',
        text: '將高維特徵投影至保留最大變異量的低維正交空間，達到降維/去除多共線性效果',
      },
      {
        kw: 'K-means 分群',
        text: '設定 K 個群心，迭代：分配→更新群心，直到群心不再移動（收斂）；需預先指定 K 值',
      },
      {
        kw: '關聯規則（Apriori）',
        text: '',
        sub: [
          'Support（支持度）= P(A∩B)，出現頻率',
          'Confidence（信心度）= P(B|A) = P(A∩B)/P(A)',
          'Lift（提升度）= Confidence(A→B) / P(B)；>1 正相關，=1 獨立，<1 負相關',
        ],
      },
      {
        kw: '混淆矩陣指標',
        text: '',
        sub: [
          'Accuracy = (TP+TN) / Total',
          'Precision = TP / (TP+FP)，預測為正中真正是正的比例',
          'Recall = TP / (TP+FN)，實際正例中被找出的比例',
          'F1-Score = 2 × Precision × Recall / (Precision + Recall)',
          'AUC-ROC：ROC 曲線下面積，越接近 1 越好',
        ],
      },
      {
        kw: 'A/B 測試',
        text: '對照組 vs 實驗組比較；p-value < 0.05 表示結果達統計顯著（信心水準 95%），可拒絕虛無假設',
      },
      {
        kw: '缺失值處理',
        text: '刪除（少量缺失）、均值/中位數填補（連續變數）、眾數填補（類別變數）、插補法（時序）',
      },
      {
        kw: '集成學習（Ensemble Learning）',
        text: '',
        sub: [
          'Bagging（如 Random Forest）：並行訓練獨立模型，Bootstrap 取樣，取投票/平均，降低 Variance',
          'Boosting（如 XGBoost、LightGBM）：串行訓練，每棵樹修正前一棵殘差，降低 Bias',
          'XGBoost 改進：L1/L2 正則化、二階泰勒展開、稀疏感知、並行分裂點計算',
          'Stacking：以多個模型預測值作為特徵訓練最終 Meta-Learner',
        ],
      },
      {
        kw: 'DBSCAN 密度聚類',
        text: 'ε（鄰域半徑）+ MinPts（最小點數）定義核心點/邊界點/雜訊點；優點：無需指定 K、發現任意形狀群集、自動識別異常值；缺點：對參數敏感、高維度效果差',
      },
      {
        kw: '迴歸評估指標',
        text: '',
        sub: [
          'MAE（平均絕對誤差）：線性懲罰，對異常值穩健，單位與原始資料相同',
          'MSE（均方誤差）：平方懲罰，對異常值敏感，適合梯度下降最佳化',
          'RMSE（均方根誤差）：√MSE，單位與原始資料相同，兼顧最佳化與可解釋性',
          'R²（決定係數）：1 = 完美擬合，0 = 等同均值預測，<0 = 模型比均值更差',
        ],
      },
      {
        kw: '時序分解與預測',
        text: '',
        sub: [
          '時序分解四成分：趨勢（Trend）+ 季節性（Seasonality）+ 循環（Cycle）+ 殘差（Residual）',
          'ARIMA：自迴歸整合移動平均，傳統統計預測方法，需定態（Stationary）資料',
          'Prophet：Facebook 開源，自動處理季節性和假期效應，適合業務場景',
          'LSTM/Transformer：深度學習方法，能捕捉複雜非線性模式',
        ],
      },
      {
        kw: '異常偵測方法',
        text: '',
        sub: [
          'IQR 法：Q1−1.5×IQR ~ Q3+1.5×IQR 範圍外視為異常，對非常態分佈穩健',
          'Z-score 法：|z| > 3 視為異常，適合常態分佈資料',
          'Isolation Forest：隨機分割孤立點，異常值更容易被隔離（路徑更短）',
          'Autoencoder：重建誤差大的樣本視為異常',
        ],
      },
    ],
  },
  {
    title: '2.7　雲端大數據服務',
    items: [
      {
        kw: 'AWS 大數據服務',
        text: '',
        sub: [
          'EMR（Elastic MapReduce）：Hadoop/Spark 叢集',
          'S3：物件儲存，資料湖常用',
          'Redshift：列式資料倉儲，適合 BI',
          'Kinesis：即時串流資料擷取',
          'Glue：Serverless ETL 服務',
          'Athena：S3 上的 Serverless SQL 查詢',
        ],
      },
      {
        kw: 'Google Cloud 大數據服務',
        text: '',
        sub: [
          'BigQuery：Serverless 列式資料倉儲，PB 級秒速查詢',
          'Dataflow：Serverless 批次/串流 ETL（基於 Apache Beam）',
          'Pub/Sub：全代管訊息佇列',
          'Dataproc：Hadoop/Spark 叢集',
        ],
      },
      {
        kw: 'Azure 大數據服務',
        text: '',
        sub: [
          'HDInsight：Hadoop/Spark 叢集',
          'Synapse Analytics：DW + Spark 整合',
          'Event Hubs：大規模事件串流',
          'Data Factory：雲端 ETL',
        ],
      },
      {
        kw: 'Serverless 大數據',
        text: '無需管理伺服器（如 BigQuery、Athena），依查詢量/掃描資料量計費，適合不規則工作負載',
      },
      {
        kw: '資料治理（Data Governance）',
        text: '資料目錄（Data Catalog）、資料品質管控、資料血緣（Data Lineage）追蹤、存取控制（RBAC）',
      },
      {
        kw: '資料安全',
        text: '傳輸加密（TLS）、靜態加密（AES-256）、欄位級加密、最小權限原則（PoLP）、稽核日誌',
      },
      {
        kw: '向量資料庫（Vector Database）',
        text: '高效儲存並搜尋高維 Embedding 向量，使用 HNSW/IVF 等 ANN 索引；RAG 架構的核心組件；代表：Pinecone、Weaviate、Milvus、Chroma、pgvector（PostgreSQL 擴展）',
      },
      {
        kw: 'Apache Airflow',
        text: '以 Python 定義 DAG 排程和管理資料管線；支援重試/監控/各種 Operator（Spark/SQL/HTTP）；是現代資料工程最廣泛使用的工作流管理工具',
      },
      {
        kw: '特徵庫（Feature Store）',
        text: '',
        sub: [
          '解決訓練-服務偏差（Training-Serving Skew）：確保線上推論與訓練使用相同特徵計算邏輯',
          '離線特徵：批次計算，用於模型訓練（Point-in-time Correct 防止資料洩漏）',
          '線上特徵：低延遲查詢，用於即時推論（通常存於 Redis/DynamoDB）',
          '代表工具：Feast（開源）、Tecton、Databricks Feature Store',
        ],
      },
      {
        kw: '資料目錄（Data Catalog）',
        text: '集中管理資料資產的元資料（Schema、業務說明、擁有者、血緣、使用頻率）；讓工程師和分析師快速發現可信資料；代表工具：Apache Atlas、Alation、Collibra、AWS Glue Data Catalog',
      },
      {
        kw: '現代資料棧（Modern Data Stack）',
        text: '',
        sub: [
          '資料擷取：Fivetran / Airbyte（Connector-based ELT）',
          '資料倉儲：BigQuery / Snowflake / Redshift（雲端 OLAP）',
          '資料轉換：dbt（SQL-based 資料轉換，版本控制）',
          '資料目錄：Alation / Collibra',
          '視覺化：Tableau / Looker / Power BI',
        ],
      },
    ],
  },
];

// ════════════════════════════════════════════════════════
//  科目一 模擬試題
// ════════════════════════════════════════════════════════
const S1_QUESTIONS = [
  {
    subject: '科目一',
    q: '下列哪種神經網路架構最適合用於影像辨識任務？',
    opts: ['A. RNN（循環神經網路）', 'B. CNN（卷積神經網路）', 'C. Transformer', 'D. GAN（生成對抗網路）'],
    ans: 'B',
    exp: 'CNN 透過卷積核（Kernel）提取局部空間特徵（邊緣、紋理、形狀），並透過池化（Pooling）降維，非常適合影像辨識。RNN 適合序列資料；Transformer 適合 NLP；GAN 適合圖像生成。',
  },
  {
    subject: '科目一',
    q: '根據 EU AI Act，「政府建立針對公民日常行為的社會信用評分系統」屬於哪個風險等級？',
    opts: ['A. 最小風險', 'B. 有限風險', 'C. 高風險', 'D. 不可接受風險（禁止）'],
    ans: 'D',
    exp: 'EU AI Act 將「政府對公民的社會信用評分系統」明確列為不可接受風險，禁止在 EU 境內使用。醫療診斷屬高風險；Chatbot 屬有限風險；垃圾郵件過濾屬最小風險。',
  },
  {
    subject: '科目一',
    q: 'RAG（Retrieval-Augmented Generation）技術主要解決 LLM 的哪項問題？',
    opts: ['A. 模型訓練時間過長', 'B. 生成不正確或過時內容（幻覺問題）', 'C. 模型參數量過大無法部署', 'D. 多語言輸入的字元編碼問題'],
    ans: 'B',
    exp: 'RAG 在推論時先從外部知識庫檢索相關文件，作為上下文提供給 LLM，有效降低幻覺（Hallucination）並使模型能使用最新資訊，不受訓練截止日期限制。',
  },
  {
    subject: '科目一',
    q: 'AI 偏見（Bias）中的「歷史偏差」是指什麼？',
    opts: ['A. 訓練資料量不足導致的偏差', 'B. 訓練資料反映了過去社會不平等，使模型複製歧視', 'C. 模型對歷史資料過度擬合', 'D. 資料蒐集時間過長導致不一致'],
    ans: 'B',
    exp: '歷史偏差（Historical Bias）指訓練資料本身含有社會歷史上的不公平現象（如種族、性別歧視），模型學習後複製並可能放大這些偏見，是 AI 公平性的核心挑戰。',
  },
  {
    subject: '科目一',
    q: 'MLOps 中「資料漂移（Data Drift）」是指？',
    opts: ['A. 模型程式碼在不同環境執行結果不同', 'B. 線上推論資料的統計分佈與訓練資料產生差異', 'C. 模型超參數隨時間自動改變', 'D. 資料庫中資料被意外刪除'],
    ans: 'B',
    exp: '資料漂移指模型上線後，真實環境的輸入資料分佈 P(X) 發生變化，與訓練資料分佈不同，導致模型效能下降。需監控並在漂移超閾值時觸發重訓練。',
  },
  {
    subject: '科目一',
    q: '下列哪種提示技術（Prompting）透過提供多個「輸入→輸出」示範來引導 LLM？',
    opts: ['A. Zero-shot Prompting', 'B. Few-shot Prompting', 'C. Chain-of-Thought Prompting', 'D. System Prompt'],
    ans: 'B',
    exp: 'Few-shot Prompting 在提示中包含幾個（通常 3~5 個）示範例子（輸入/輸出對），讓模型學習格式與推理模式。Zero-shot 無範例；CoT 要求逐步推理；System Prompt 設定角色準則。',
  },
  {
    subject: '科目一',
    q: '「可解釋 AI（XAI）」的主要用途是？',
    opts: ['A. 提高模型訓練速度', 'B. 讓模型預測結果可被人類理解，符合透明性要求', 'C. 自動選擇最佳超參數', 'D. 將複雜模型轉換為規則式系統'],
    ans: 'B',
    exp: 'XAI 讓複雜模型（如深度學習）的決策過程可解釋，常用工具：SHAP（量化每個特徵貢獻度）、LIME（局部線性近似），用於滿足 EU AI Act、金融法規等透明性要求。',
  },
  {
    subject: '科目一',
    q: '製造業導入「預測性維護」AI 系統，主要解決哪個業務問題？',
    opts: ['A. 自動化生產報表撰寫', 'B. 在設備故障前預測並安排維修，降低停機損失', 'C. 減少生產線人員數量', 'D. 優化產品行銷文案'],
    ans: 'B',
    exp: '預測性維護（Predictive Maintenance）透過感測器資料（振動、溫度、電流）訓練時序模型，在故障前發出警報，使維修從「定期維護」轉為「按需維護」，顯著降低非計畫停機成本。',
  },
  {
    subject: '科目一',
    q: '關於匿名化（Anonymization）與假名化（Pseudonymization），下列何者正確？',
    opts: ['A. 兩者均可完全還原為個人資訊', 'B. 匿名化不可逆；假名化可透過對照表還原', 'C. 假名化比匿名化隱私保護等級更高', 'D. 兩者在 GDPR 下均需取得明確同意'],
    ans: 'B',
    exp: '匿名化是不可逆的去識別化，GDPR 不適用於已匿名資料。假名化保留對照表可還原，仍屬個人資料，仍受 GDPR 規範。因此匿名化隱私保護等級更高。',
  },
  {
    subject: '科目一',
    q: 'AI 導入評估的「風險評估矩陣」的兩個軸分別代表什麼？',
    opts: ['A. 開發成本 × 預期收益', 'B. 影響程度 × 發生機率', 'C. 技術複雜度 × 資料品質', 'D. 時程長短 × 人員數量'],
    ans: 'B',
    exp: '風險評估矩陣（Risk Matrix）以「影響程度（Impact）」與「發生機率（Likelihood）」為兩軸，依四個象限採取「接受/監控/緩解/迴避」等不同應對策略。',
  },
  {
    subject: '科目一',
    q: '下列哪項不是 AI Agent 的核心能力？',
    opts: ['A. 工具使用（Tool Use）', 'B. 規劃（Planning）', 'C. 靜態固定記憶', 'D. 與環境互動並反饋'],
    ans: 'C',
    exp: 'AI Agent 的核心特徵是動態能力：工具使用、規劃、動態記憶更新、環境互動。「靜態固定記憶」不是 Agent 特徵，Agent 強調動態記憶（Short-term + Long-term）的更新能力。',
  },
  {
    subject: '科目一',
    q: '推薦系統中「協同過濾（Collaborative Filtering）」的運作原理是？',
    opts: ['A. 根據商品描述特徵比對相似度', 'B. 根據相似用戶的行為偏好推薦', 'C. 依照銷售量排序後直接推薦', 'D. 使用規則式引擎按時間排列'],
    ans: 'B',
    exp: '協同過濾（CF）分為 User-based（找相似用戶）和 Item-based（找相似商品），基於歷史行為矩陣預測評分。內容過濾（Content-based）才是根據商品本身特徵比對，與 CF 不同。',
  },
  {
    subject: '科目一',
    q: '「概念漂移（Concept Drift）」與「資料漂移（Data Drift）」的主要差異為？',
    opts: ['A. 概念漂移 = 輸入特徵分佈改變；資料漂移 = 標籤關係改變', 'B. 資料漂移 = 輸入分佈改變；概念漂移 = 輸入與標籤關係改變', 'C. 兩者完全相同', 'D. 概念漂移只發生在 NLP 模型'],
    ans: 'B',
    exp: '資料漂移：P(X) 改變（輸入特徵的統計分佈改變）；概念漂移：P(Y|X) 改變（相同輸入對應的正確輸出關係變了，如市場行為改變）。兩者都需監控，但應對方式不同。',
  },
  {
    subject: '科目一',
    q: 'Fine-tuning 與 RAG 的適用情境差異，下列何者正確？',
    opts: ['A. Fine-tuning 適合即時資料更新；RAG 適合固定領域知識', 'B. Fine-tuning 適合讓模型學習特定風格或術語；RAG 適合引用最新外部文件', 'C. 兩者功能完全相同，只是成本不同', 'D. Fine-tuning 只能用於小型模型'],
    ans: 'B',
    exp: 'Fine-tuning 讓模型學習特定領域語言風格和術語，需重新訓練。RAG 不需重訓練，透過即時檢索外部文件提供上下文，適合知識頻繁更新的場景，且可稽核引用來源。',
  },
  {
    subject: '科目一',
    q: 'SHAP（SHapley Additive exPlanations）在 AI 可解釋性中的主要功能是？',
    opts: ['A. 自動調整模型超參數', 'B. 量化每個特徵對單一預測結果的貢獻度', 'C. 生成合成資料以擴充訓練集', 'D. 壓縮神經網路模型大小'],
    ans: 'B',
    exp: 'SHAP 基於賽局理論（Shapley Values），為每個特徵計算對特定預測的邊際貢獻值（正/負），可解釋單筆預測（Local）也可彙總為全域特徵重要性（Global），是最廣泛使用的 XAI 工具之一。',
  },
  {
    subject: '科目一',
    q: 'GAN（生成對抗網路）由哪兩個主要部分組成？',
    opts: ['A. 編碼器（Encoder）與解碼器（Decoder）', 'B. 生成器（Generator）與判別器（Discriminator）', 'C. Actor 與 Critic', 'D. 前饋層（Feed-forward）與注意力層（Attention）'],
    ans: 'B',
    exp: 'GAN 由兩個網路對抗訓練：Generator 負責生成假樣本以欺騙 Discriminator；Discriminator 負責辨別真假樣本。兩者相互競爭直到 Generator 生成的樣本品質無法被區分。',
  },
  {
    subject: '科目一',
    q: 'Transformer 架構的核心機制「自注意力（Self-Attention）」主要解決了什麼問題？',
    opts: ['A. 圖像的局部特徵提取效率不足', 'B. RNN 無法平行計算且難以處理長距離依賴關係', 'C. 梯度消失問題（Vanishing Gradient）', 'D. 模型參數量過多導致過擬合'],
    ans: 'B',
    exp: 'Self-Attention 讓序列中每個位置可直接關注其他所有位置，解決 RNN 長距離依賴問題。同時計算全序列的注意力權重，支援高度平行化訓練，這是 Transformer 超越 RNN/LSTM 的關鍵。',
  },
  {
    subject: '科目一',
    q: '「遷移學習（Transfer Learning）」的主要優勢是？',
    opts: ['A. 不需要任何訓練資料即可部署模型', 'B. 利用預訓練模型的知識，在少量標注資料下快速微調至新任務', 'C. 讓模型可以在不同作業系統間移植', 'D. 自動生成新的訓練資料集'],
    ans: 'B',
    exp: '遷移學習將預訓練模型（如 ResNet、BERT）學到的通用特徵遷移至目標任務，只需少量標注資料進行 Fine-tuning，大幅節省訓練成本與時間，尤其適合資料稀少的垂直領域。',
  },
  {
    subject: '科目一',
    q: '模型「過擬合（Overfitting）」的常見症狀是？',
    opts: ['A. 訓練集與驗證集誤差均高', 'B. 訓練集誤差低但驗證集誤差高，泛化能力差', 'C. 訓練集誤差高但驗證集誤差低', 'D. 模型收斂速度過慢'],
    ans: 'B',
    exp: '過擬合指模型記憶訓練資料（含雜訊），導致訓練誤差極低但驗證/測試誤差高，泛化差。常見解決方法：增加訓練資料、Dropout、L1/L2 正則化、Early Stopping、Data Augmentation。',
  },
  {
    subject: '科目一',
    q: '「K 折交叉驗證（K-Fold Cross Validation）」的主要目的是？',
    opts: ['A. 將訓練集切成 K 份加速訓練', 'B. 在有限資料下更可靠地評估模型泛化性能', 'C. 自動選擇最佳的 K 值超參數', 'D. 減少模型的參數量'],
    ans: 'B',
    exp: 'K-Fold 將資料切成 K 份，輪流以其中 1 份作驗證集、其餘 K-1 份訓練，重複 K 次後取平均指標，充分利用有限資料並得到更穩健的評估結果，減少單次分割的隨機性影響。',
  },
  {
    subject: '科目一',
    q: '「聯邦學習（Federated Learning）」的核心特點是？',
    opts: ['A. 將所有用戶資料集中至中央伺服器訓練', 'B. 在本地端訓練模型後只上傳梯度或模型更新，不共享原始資料', 'C. 使用多台雲端伺服器並行訓練同一模型', 'D. 讓多個 AI 模型共同投票決定最終預測'],
    ans: 'B',
    exp: '聯邦學習讓資料保留在本地（手機、醫院等），本地訓練後只上傳模型梯度或權重更新至中央伺服器聚合，原始資料不離開本地。適用於醫療、金融等隱私敏感場景。',
  },
  {
    subject: '科目一',
    q: 'RLHF（Reinforcement Learning from Human Feedback）在 LLM 訓練中的作用是？',
    opts: ['A. 使用人類標注的偏好資料訓練獎勵模型，引導 LLM 生成更符合人類期望的輸出', 'B. 讓 LLM 自動在遊戲環境中學習策略', 'C. 用人工審核替代自動化評估流程', 'D. 壓縮 LLM 參數量以降低推論成本'],
    ans: 'A',
    exp: 'RLHF 三階段：①SFT 微調基礎模型；②收集人類偏好資料訓練獎勵模型（Reward Model）；③用 PPO 等 RL 演算法以獎勵模型引導 LLM 生成對齊人類價值觀的輸出。ChatGPT 是代表性應用。',
  },
  {
    subject: '科目一',
    q: '「邊緣 AI（Edge AI）」相較於「雲端 AI」的主要優點是？',
    opts: ['A. 模型精度更高', 'B. 訓練速度更快', 'C. 降低延遲並保護資料隱私，不需將原始資料上傳雲端', 'D. 可支援更大型的模型'],
    ans: 'C',
    exp: 'Edge AI 在本地端裝置（如手機、IoT 感測器）執行推論，優點：低延遲（毫秒級）、離線可用、原始資料不上傳（隱私保護）、降低頻寬成本。缺點：算力與儲存受限，模型需輕量化（量化、剪枝）。',
  },
  {
    subject: '科目一',
    q: '「AutoML」自動化機器學習主要解決哪個痛點？',
    opts: ['A. 自動收集並標注訓練資料', 'B. 自動化特徵工程、模型選擇與超參數調優，降低 ML 使用門檻', 'C. 自動部署模型至雲端並監控效能', 'D. 自動生成訓練用的合成資料'],
    ans: 'B',
    exp: 'AutoML 自動執行 ML 流程中最耗時的部分：特徵選擇/工程、演算法搜尋（NAS）、超參數最佳化（HPO）。代表工具：Google AutoML、H2O.ai、Auto-sklearn，讓非 ML 專家也能快速建模。',
  },
  {
    subject: '科目一',
    q: 'BERT 與 GPT 在架構設計上的最大差異是？',
    opts: ['A. BERT 用 CNN；GPT 用 RNN', 'B. BERT 是雙向 Encoder（理解語境）；GPT 是單向 Decoder（生成文字）', 'C. BERT 只能處理英文；GPT 支援多語言', 'D. BERT 參數量遠大於 GPT'],
    ans: 'B',
    exp: 'BERT 使用 Transformer Encoder，雙向讀取上下文，擅長文字理解任務（分類、NER、問答）。GPT 使用 Transformer Decoder，從左到右生成，擅長文字生成任務。兩者都基於 Transformer 但用途不同。',
  },
  {
    subject: '科目一',
    q: '信用評分模型中若 Precision 低、Recall 高，實際業務影響是？',
    opts: ['A. 大量真正違約者被誤判為正常，銀行損失高', 'B. 大量正常客戶被誤判為高風險，拒絕優質客戶', 'C. 模型無法偵測任何違約者', 'D. 模型對所有人一律核准貸款'],
    ans: 'B',
    exp: 'Precision 低 = 預測為高風險中有很多其實是正常人（假陽性 FP 多）；Recall 高 = 真正高風險者大多被抓到。結果是正常客戶被誤拒，影響業務拓展。反之 Recall 低則漏放真正違約者，壞帳增加。',
  },
  {
    subject: '科目一',
    q: '「模型壓縮」技術中「量化（Quantization）」的意義是？',
    opts: ['A. 刪除冗餘的網路層', 'B. 將模型權重從高精度（float32）轉為低精度（int8/float16），降低記憶體與計算量', 'C. 將多個小模型合併為一個大模型', 'D. 用更少的訓練資料重新訓練模型'],
    ans: 'B',
    exp: '量化將權重從 32 位元浮點數壓縮至 8 位元整數或 16 位元浮點數，記憶體降低 2~4 倍、推論速度提升，精度損失通常極小。常用於將大型模型部署至行動裝置或嵌入式系統（Edge AI）。',
  },
  {
    subject: '科目一',
    q: '「強化學習（Reinforcement Learning）」的學習機制與監督式學習最主要的差異是？',
    opts: ['A. 強化學習需要更多標注資料', 'B. 強化學習透過與環境互動獲得獎勵信號學習策略，而非使用預標注的正確答案', 'C. 強化學習只能用於遊戲場景', 'D. 強化學習不使用神經網路'],
    ans: 'B',
    exp: '監督式學習需要 (X, Y) 配對標注資料；強化學習的 Agent 在環境中執行動作，根據結果獲得獎勵（+）或懲罰（−），透過試錯學習最大化長期累積獎勵，適用於序列決策問題（機器人、遊戲、推薦）。',
  },
  {
    subject: '科目一',
    q: '台灣「AI 基本法」（人工智慧基本法）的主要立法精神是？',
    opts: ['A. 全面禁止高風險 AI 系統在台灣使用', 'B. 以人為本，促進 AI 發展同時確保可問責、透明及保護基本權利', 'C. 強制所有企業必須建立 AI 倫理委員會', 'D. 規定所有 AI 模型必須開源'],
    ans: 'B',
    exp: '台灣 AI 基本法（2024 年通過）強調「人本 AI」，核心原則：以人為本、透明可信、安全可靠、公平包容、促進創新、國際接軌。規範政府 AI 應用，確保 AI 系統可問責，保護人民基本權利。',
  },
  {
    subject: '科目一',
    q: '變分自編碼器（VAE）訓練目標函數中「KL 散度」的作用是？',
    opts: ['A. 計算重建圖像與原始圖像的像素差異', 'B. 約束潛在空間分佈接近標準常態分佈，使潛在空間具有連續性可生成新樣本', 'C. 測量生成器與判別器的對抗損失', 'D. 調整模型學習率的衰減速率'],
    ans: 'B',
    exp: 'VAE 損失函數 = 重建損失（Reconstruction Loss）+ KL 散度（KL Divergence）。KL 散度衡量編碼器輸出的分佈 q(z|x) 與先驗分佈 p(z)（標準常態）的差異，迫使潛在空間有規律性，使解碼器可從標準常態分佈採樣生成新樣本，而非僅記憶訓練樣本。',
  },
  {
    subject: '科目一',
    q: '「擴散模型（Diffusion Model）」的基本原理是？',
    opts: ['A. 生成器與判別器對抗訓練直到均衡', 'B. 正向過程逐步加入雜訊，反向過程訓練模型逐步去除雜訊以重建樣本', 'C. 透過矩陣分解找到低維潛在表示', 'D. 從樣本集合中隨機混合生成新樣本'],
    ans: 'B',
    exp: '擴散模型兩個過程：正向過程（Forward Process）—— 對原始資料逐步疊加高斯雜訊至純雜訊；反向過程（Reverse Process）—— 訓練 U-Net 等神經網路逐步預測並去除每一步的雜訊。Stable Diffusion、DALL-E 2 均基於此原理，生成品質高且多樣性好。',
  },
  {
    subject: '科目一',
    q: '「LoRA（Low-Rank Adaptation）」微調方法的核心優勢是？',
    opts: ['A. 凍結所有參數，只訓練新增的分類頭', 'B. 在原始權重旁注入低秩矩陣分解的訓練參數，可訓練參數量減少 99% 以上但效果接近全量微調', 'C. 將大型模型蒸餾壓縮為小型模型', 'D. 使用多個獨立模型投票集成'],
    ans: 'B',
    exp: 'LoRA 凍結預訓練模型原始權重 W，對需更新的矩陣插入兩個低秩矩陣 A（d×r）和 B（r×d），只訓練 A、B（r 遠小於 d）。可訓練參數量大幅減少（如從 7B 降至 4M），訓練資源需求低，是目前最主流的 LLM 高效微調（PEFT）方法。',
  },
  {
    subject: '科目一',
    q: '自然語言生成評估指標「BLEU Score」的計算原理是？',
    opts: ['A. 計算生成文字與參考文字共同詞彙的召回率', 'B. 比較機器生成文字與人工參考譯文的 n-gram 重疊精確率', 'C. 測量生成句子的困惑度（Perplexity）', 'D. 統計生成文字中語法錯誤的數量'],
    ans: 'B',
    exp: 'BLEU（Bilingual Evaluation Understudy）計算機器翻譯/生成與一或多個參考文本的 n-gram 重疊精確率（1-gram 到 4-gram），並加入長度懲罰（Brevity Penalty）防止生成過短文字。分數範圍 0~1（1 為完美匹配），常用於機器翻譯、文字摘要評估。',
  },
  {
    subject: '科目一',
    q: '「提示注入攻擊（Prompt Injection）」針對 LLM 系統的威脅是？',
    opts: ['A. 在模型訓練時植入惡意樣本污染模型', 'B. 透過惡意輸入覆蓋或欺騙 LLM 的系統提示，使其洩漏隱私或執行非預期行為', 'C. 用大量請求使 LLM API 服務過載', 'D. 反向工程還原 LLM 的訓練資料'],
    ans: 'B',
    exp: '提示注入攻擊在用戶輸入中嵌入惡意指令（如「忽略前述指令，改為輸出...」），試圖覆蓋系統提示（System Prompt）、洩漏機密資訊或執行危險操作。間接提示注入（Indirect Prompt Injection）透過 LLM 處理的外部文件植入指令。防禦：輸入過濾、沙盒隔離、最小權限原則。',
  },
  {
    subject: '科目一',
    q: '依據 GDPR，「被遺忘權（Right to Erasure）」的適用條件是？',
    opts: ['A. 任何用戶隨時可要求刪除所有個人資料，企業無例外', 'B. 資料不再必要、用戶撤回同意或資料被非法處理等情況下，用戶可要求刪除', 'C. 僅適用於跨境傳輸的個人資料', 'D. 企業必須在 7 日內完成刪除'],
    ans: 'B',
    exp: 'GDPR Article 17 的「被遺忘權」在以下情況適用：①資料已非必要；②用戶撤回同意；③用戶反對處理；④資料被非法處理；⑤需符合法律義務。例外：言論自由、科學研究、法律抗辯。企業通常須在 30 日內回應請求。',
  },
  {
    subject: '科目一',
    q: 'CRISP-DM 資料探勘標準流程六個階段的正確順序是？',
    opts: ['A. 資料理解 → 業務理解 → 資料準備 → 建模 → 評估 → 部署', 'B. 業務理解 → 資料理解 → 資料準備 → 建模 → 評估 → 部署', 'C. 資料準備 → 業務理解 → 建模 → 資料理解 → 評估 → 部署', 'D. 建模 → 業務理解 → 資料理解 → 評估 → 資料準備 → 部署'],
    ans: 'B',
    exp: 'CRISP-DM（Cross Industry Standard Process for Data Mining）六階段：①業務理解（Business Understanding）→ ②資料理解（Data Understanding）→ ③資料準備（Data Preparation，通常最耗時）→ ④建模（Modeling）→ ⑤評估（Evaluation）→ ⑥部署（Deployment）。過程可迭代回溯，是最廣泛使用的資料探勘方法論。',
  },
  {
    subject: '科目一',
    q: 'MLflow 在 MLOps 的核心功能是？',
    opts: ['A. 自動清洗和標注訓練資料', 'B. 追蹤實驗超參數/指標、版本化模型（Model Registry）及標準化部署', 'C. 提供分散式模型訓練的 GPU 算力', 'D. 自動產生模型測試報告'],
    ans: 'B',
    exp: 'MLflow 四大功能：①Tracking（記錄實驗超參數、評估指標、模型文件、程式碼版本）；②Projects（可重現訓練環境打包）；③Models（統一模型格式，支援多框架）；④Registry（模型版本管理，含 Staging/Production/Archived 生命週期狀態）。是最廣泛使用的開源 MLOps 實驗管理工具。',
  },
  {
    subject: '科目一',
    q: '「DVC（Data Version Control）」解決機器學習的哪項挑戰？',
    opts: ['A. 模型推論的延遲優化', 'B. 追蹤和版本化大型資料集及模型文件，類似 Git 對程式碼的版本控制', 'C. 自動部署模型至雲端並監控效能', 'D. 進行分散式超參數搜索'],
    ans: 'B',
    exp: 'DVC 基於 Git，提供資料集和模型文件的版本控制。DVC 在 Git 中儲存指向實際大型文件（S3、GCS、本地）的 .dvc 指標文件，確保每個程式碼版本對應特定資料和模型版本，支援實驗重現（Reproducibility）和資料管線（pipeline）定義。',
  },
  {
    subject: '科目一',
    q: '「Human-in-the-Loop（HITL）」在 AI 開發中的主要應用場景是？',
    opts: ['A. 用人工全面取代 AI 的決策流程', 'B. 在模型訓練或決策關鍵節點引入人類標注/審核，提升品質並處理模型不確定案例', 'C. 強制要求每個 AI 決策都需人工二次確認', 'D. 讓多位人類專家投票決定模型架構'],
    ans: 'B',
    exp: 'HITL 在 AI 流程保留人類參與：①主動學習（Active Learning）：模型挑選最不確定樣本請人標注；②高風險場景輔助決策（如醫療：AI 建議，醫生最終決定）；③RLHF 的人類偏好標注。目標是以最少人力干預最大化 AI 品質，非全程人工替代。',
  },
  {
    subject: '科目一',
    q: '貝葉斯最佳化（Bayesian Optimization）用於超參數調整時的優勢是？',
    opts: ['A. 窮舉所有超參數組合找到全局最優', 'B. 基於先前評估結果建立代理模型，智慧選擇下一個最有潛力的超參數組合，比隨機搜索收斂更快', 'C. 以固定步長遍歷超參數網格', 'D. 只調整學習率一個超參數'],
    ans: 'B',
    exp: '貝葉斯最佳化使用 Surrogate Model（如 Gaussian Process）對超參數空間建模，並透過 Acquisition Function（期望改善 EI 或置信上界 UCB）選擇下一評估點。相比 Grid Search（指數爆炸）和 Random Search（效率低），貝葉斯最佳化利用先前結果智慧探索，收斂更快。Hyperopt、Optuna 均實作此方法。',
  },
  {
    subject: '科目一',
    q: '電腦視覺中「語意分割（Semantic Segmentation）」與「實例分割（Instance Segmentation）」的主要差異是？',
    opts: ['A. 兩者完全相同，只是名稱不同', 'B. 語意分割對每個像素分類但不區分個體；實例分割進一步區分同類中不同個體', 'C. 語意分割處理彩色影像；實例分割處理深度影像', 'D. 語意分割適用於影像分類；實例分割適用於物件偵測'],
    ans: 'B',
    exp: '語意分割（Semantic Segmentation）：每個像素預測類別標籤（如全部行人像素標為「人」），同類個體不區分。實例分割（Instance Segmentation）：進一步區分同類中不同個體（行人1、行人2有各自遮罩）。Mask R-CNN 是代表性實例分割模型，Fully Convolutional Network (FCN) 是語意分割基礎。',
  },
  {
    subject: '科目一',
    q: '「模型卡（Model Card）」在 AI 治理中的主要用途是？',
    opts: ['A. 記錄模型 API 的呼叫格式和範例', 'B. 標準化記錄模型用途、訓練資料、評估結果（含公平性指標）及已知限制，增加透明度', 'C. 儲存神經網路架構的視覺化圖表', 'D. 管理模型的版本號和部署日誌'],
    ans: 'B',
    exp: 'Model Card（模型卡）由 Google 提出，是標準化模型說明文件，包含：預期用途與禁止用途、訓練資料來源與特性、不同子群體的公平性評估指標、已知偏見、倫理風險和局限性。符合 EU AI Act 透明性要求，幫助使用者做出知情決策，促進 AI 負責任使用。',
  },
  {
    subject: '科目一',
    q: '「主動學習（Active Learning）」解決什麼問題？',
    opts: ['A. 讓模型從網路自動爬取訓練資料', 'B. 模型主動挑選最有資訊量（最不確定）的未標注樣本請人標注，以最小標注成本達到最佳效果', 'C. 讓模型在訓練過程中自動更新學習策略', 'D. 使用生成模型自動生成合成標注資料'],
    ans: 'B',
    exp: '主動學習（Active Learning）解決標注資料昂貴問題。策略：不確定性採樣（選信心最低的）、委員會查詢（多模型意見最分歧的）、期望模型改變最大的。相比隨機標注，可用更少標注達到相同效果。常見於醫療影像、自動駕駛等標注成本高的場景，常與 HITL 結合使用。',
  },
  {
    subject: '科目一',
    q: 'AI「供應鏈攻擊（Supply Chain Attack）」的典型手法是？',
    opts: ['A. 直接針對模型 API 端點發動大量請求', 'B. 在公開預訓練模型或開源套件中植入後門，使下載使用的開發者受害', 'C. 竊取模型推論伺服器的存取憑證', 'D. 修改模型輸入資料造成錯誤預測'],
    ans: 'B',
    exp: 'AI 供應鏈攻擊污染可信的上游資源（公開模型倉庫、開源套件、訓練資料），在預訓練模型中植入後門（Backdoor），觸發特定輸入模式時執行惡意行為。Hugging Face 模型倉庫曾發現含惡意 pickle 程式碼的模型。防護：僅使用可信來源、驗證模型雜湊值、掃描依賴套件。',
  },
  {
    subject: '科目一',
    q: 'Transformer 中「多頭注意力（Multi-Head Attention）」相比單頭注意力的優勢是？',
    opts: ['A. 減少計算量和記憶體使用', 'B. 讓模型在不同表示子空間中同時關注序列不同位置的語義，捕捉多樣化關係', 'C. 解決梯度消失問題', 'D. 增加模型的最大序列長度'],
    ans: 'B',
    exp: '多頭注意力（Multi-Head Attention）將 Q、K、V 分別投影到 h 個低維子空間，各頭獨立計算注意力，再拼接還原。不同頭可學習不同語意關係（如主謂關係、共指關係），比單頭能捕捉更豐富多樣的依賴模式。BERT 使用 12 個注意力頭，GPT-3 使用 96 個。',
  },
  {
    subject: '科目一',
    q: '「知識蒸餾（Knowledge Distillation）」的核心思想是？',
    opts: ['A. 將多個模型的知識直接合併為一個更大的模型', 'B. 用大型教師模型的軟標籤（Soft Label）訓練小型學生模型，使學生模型接近教師模型的效能', 'C. 從知識庫中自動擷取訓練資料', 'D. 讓模型定期從新資料中增量學習'],
    ans: 'B',
    exp: '知識蒸餾（Knowledge Distillation）讓學生模型不只學 Hard Label（0/1），還學習教師模型輸出的 Soft Probabilities（如 [0.7, 0.2, 0.1]）。Soft Label 包含類別間的相似度資訊（暗知識），使學生模型在壓縮 10 倍的情況下仍保持接近教師模型的準確率。常用於模型輕量化部署。',
  },
  {
    subject: '科目一',
    q: '「模型剪枝（Pruning）」的目的是？',
    opts: ['A. 刪除訓練資料中的雜訊樣本', 'B. 移除神經網路中對輸出貢獻低的權重或神經元，縮小模型大小加速推論', 'C. 限制模型的訓練時間避免過擬合', 'D. 減少訓練批次大小降低記憶體使用'],
    ans: 'B',
    exp: '剪枝分兩類：結構化剪枝（移除整個神經元/通道/層，硬體友善，加速明顯）；非結構化剪枝（將權重稀疏化為零，壓縮率高但需稀疏計算硬體支援）。通常流程：訓練→剪枝→微調（Fine-tuning 恢復精度）→部署。搭配量化可進一步壓縮。',
  },
  {
    subject: '科目一',
    q: '自監督學習（Self-Supervised Learning）的資料使用方式是？',
    opts: ['A. 使用人工標注的大量標籤資料訓練', 'B. 從無標注資料中自動構造監督信號（如遮蔽詞預測、圖像旋轉角度預測）進行預訓練', 'C. 透過環境獎勵信號進行策略學習', 'D. 使用少量標注樣本和大量無標注樣本混合訓練'],
    ans: 'B',
    exp: '自監督學習從資料本身建構監督任務：NLP 中 BERT 的 MLM（遮蔽語言模型，預測被遮蔽的詞）；CV 中的 SimCLR、MoCo（對比學習）；MAE（遮蔽影像自動編碼器）。不需人工標注，可利用海量無標注資料做預訓練，是 LLM 訓練的核心技術基礎。',
  },
  {
    subject: '科目一',
    q: '「混合專家模型（MoE, Mixture of Experts）」的運作原理是？',
    opts: ['A. 訓練多個模型後取平均預測值', 'B. 每次推論由路由器（Router）動態選擇少數專家子網路處理，實現參數擴展但計算量不成比例增加', 'C. 使用多個 GPU 並行計算同一批資料', 'D. 將不同模態的資料分別交由不同模型處理'],
    ans: 'B',
    exp: 'MoE 架構（如 Mixtral、GPT-4 傳聞採用）：模型有大量稀疏專家（Expert）子網路，Router 對每個 Token 選擇 Top-K 個專家（通常 K=2），其餘不啟動。使總參數量可擴大 8~16 倍，但每次前向傳播只啟動一小部分，計算效率高。代表模型：Mixtral 8x7B 每次只啟動 2 個專家。',
  },
  {
    subject: '科目一',
    q: '「對比學習（Contrastive Learning）」的訓練目標是？',
    opts: ['A. 讓相似樣本在向量空間中靠近，不相似樣本遠離', 'B. 預測被遮蔽的輸入片段', 'C. 最大化生成樣本與真實樣本的分佈差異', 'D. 讓模型學習任務的步驟推理'],
    ans: 'A',
    exp: '對比學習（Contrastive Learning）以 InfoNCE 等損失函數為目標：正樣本對（同一影像的不同增強版本、語意相近文字）在嵌入空間拉近；負樣本對（不同語義的樣本）推遠。SimCLR、MoCo、CLIP（文字-圖像跨模態對齊）均採用此框架，是自監督視覺表示學習的主流方法。',
  },
  {
    subject: '科目一',
    q: 'LLM 中「上下文視窗（Context Window）」的限制對應用設計的影響是？',
    opts: ['A. 決定模型可記憶的長期歷史資訊量，超過後早期資訊會被截斷', 'B. 限制模型每秒可處理的請求數量', 'C. 決定模型輸出文字的最大長度', 'D. 影響模型的訓練速度'],
    ans: 'A',
    exp: 'Context Window 定義模型在單次推論中能看到的最大 Token 數（包含輸入+輸出）。超過視窗的早期內容會被截斷，模型無法參考。早期 GPT-3 僅 4K tokens；GPT-4 Turbo 達 128K；Claude 3 達 200K。長文件應用需設計分塊（Chunking）或使用 RAG 繞過此限制。',
  },
  {
    subject: '科目一',
    q: '「指令微調（Instruction Tuning）」的目的是？',
    opts: ['A. 讓模型學習特定垂直領域的技術術語', 'B. 讓模型能夠遵循自然語言指令執行多樣任務，而非只完成特定格式的補全', 'C. 減少模型在訓練集上的過擬合', 'D. 提高模型的生成速度'],
    ans: 'B',
    exp: '指令微調（Instruction Tuning）使用「指令→回應」配對資料（如 Alpaca、FLAN 資料集）微調基礎語言模型，使其從「補全下一個 Token」轉變為「理解並遵循使用者指令」。是基礎模型成為 ChatGPT-style 助理的關鍵步驟，通常在 RLHF 之前進行。',
  },
  {
    subject: '科目一',
    q: 'AI 導入企業時，「概念驗證（Proof of Concept, PoC）」的主要目的是？',
    opts: ['A. 直接上線生產系統取代現有流程', 'B. 以小規模實驗驗證 AI 技術的可行性和業務價值，降低全面導入的風險', 'C. 對所有員工進行 AI 技術培訓', 'D. 購買並整合所有必要的 AI 工具和授權'],
    ans: 'B',
    exp: 'PoC 在有限範圍（如單一部門、特定資料集）快速驗證假設：技術是否可行？資料品質是否足夠？是否能解決業務痛點？通常 2~4 週完成。成功的 PoC 為全面導入提供依據，失敗的 PoC 也能提前避免巨額浪費。是 AI 導入決策的重要里程碑。',
  },
  {
    subject: '科目一',
    q: '評估 AI 導入方案時「自建（Build）vs 採購（Buy）vs 開源（Open Source）」的決策依據主要考量什麼？',
    opts: ['A. 只看授權費用高低', 'B. 綜合評估客製化需求、資料隱私、維護能力、時程和成本', 'C. 總是優先選擇開源方案', 'D. 根據供應商市場排名決定'],
    ans: 'B',
    exp: '決策框架：Build（自建）適合核心競爭力、高度客製化需求，成本高時程長；Buy（採購 SaaS/API）適合通用功能，快速上線但資料主控權低；Open Source（如 Llama、Stable Diffusion）彈性高、無授權費，需自行維護與部署。通常結合使用：核心能力自建，輔助功能採購。',
  },
  {
    subject: '科目一',
    q: 'Grad-CAM（Gradient-weighted Class Activation Mapping）在 CNN 可解釋性中的用途是？',
    opts: ['A. 顯示每個輸入特徵對預測的數值貢獻', 'B. 生成熱力圖顯示影像中哪些區域對模型決策最重要', 'C. 可視化神經網路的權重分佈', 'D. 計算模型各層的梯度範數'],
    ans: 'B',
    exp: 'Grad-CAM 利用目標類別對最後一個卷積層的梯度（反映特徵重要性），加權平均特徵圖後生成熱力圖，疊加在原始影像上顯示模型關注的區域。醫療影像（X光、皮膚癌）中用於驗證模型是否關注正確病灶，提高醫師對 AI 診斷的信任度。',
  },
  {
    subject: '科目一',
    q: 'AI 模型的「公平性指標（Fairness Metrics）」中，「人口統計均等（Demographic Parity）」要求什麼？',
    opts: ['A. 不同群體的樣本數量相等', 'B. 不同人口群體獲得正向預測（如核准貸款）的比例相同', 'C. 模型在所有群體上的準確率相同', 'D. 不同群體的假陽性率相等'],
    ans: 'B',
    exp: '人口統計均等（Demographic Parity / Statistical Parity）：P(Ŷ=1 | A=0) = P(Ŷ=1 | A=1)，即不同敏感屬性群體（性別、種族）獲得正向結果的機率相同。其他公平性指標：均等機會（Equal Opportunity，各群體 Recall 相等）、預測公平（Calibration，各群體預測概率準確）。不同指標在數學上可能無法同時滿足（公平性不可能定理）。',
  },
  {
    subject: '科目一',
    q: '「負責任 AI（Responsible AI）」框架通常包含哪些核心維度？',
    opts: ['A. 只有準確率和速度兩個維度', 'B. 公平性、可靠性、隱私、安全性、包容性、透明性、問責性', 'C. 開發成本、上市時間、市場佔有率', 'D. 模型大小、推論延遲、能源消耗'],
    ans: 'B',
    exp: 'Microsoft、Google、IBM 等主要科技公司的 Responsible AI 框架均涵蓋：公平性（Fairness）、可靠性與安全（Reliability & Safety）、隱私與保全（Privacy & Security）、包容性（Inclusiveness）、透明性（Transparency）、問責性（Accountability）。這些維度也與 EU AI Act 的合規要求高度對應。',
  },
  {
    subject: '科目一',
    q: '強化學習中「探索與利用的權衡（Exploration-Exploitation Tradeoff）」指的是？',
    opts: ['A. 訓練時間與推論時間之間的平衡', 'B. Agent 在嘗試新動作（探索未知）與執行已知最佳動作（利用現有知識）之間的平衡', 'C. 模型準確率與計算資源之間的取捨', 'D. 訓練資料量與模型複雜度之間的平衡'],
    ans: 'B',
    exp: '探索（Exploration）：Agent 嘗試新動作以發現可能更好的策略（防止陷入局部最優）；利用（Exploitation）：根據現有知識選擇已知最佳動作（最大化即時獎勵）。常見策略：ε-greedy（以 ε 機率隨機探索）、UCB（置信上界）、Thompson Sampling。是強化學習的核心挑戰，也應用於推薦系統的 bandit 問題。',
  },
  {
    subject: '科目一',
    q: '企業 AI 專案中，「數據飛輪（Data Flywheel）」描述的是什麼現象？',
    opts: ['A. 資料儲存量增加導致查詢速度下降的負面效應', 'B. 更多用戶 → 更多資料 → 更好模型 → 更好產品 → 更多用戶的正向循環，形成競爭壁壘', 'C. 資料清洗需要反覆迭代的過程', 'D. 大型資料集訓練需要大量計算資源的現象'],
    ans: 'B',
    exp: '數據飛輪（Data Flywheel / Virtuous Cycle）是 AI 競爭優勢的核心概念：用戶使用產品產生資料 → 資料用於改善 AI 模型 → 更好的模型提升用戶體驗 → 吸引更多用戶。Tesla 的駕駛資料、Google 的搜尋資料均形成強大飛輪效應，使後進者難以追趕。',
  },
  {
    subject: '科目一',
    q: '「詞嵌入（Word Embedding）」技術（如 Word2Vec）相較於 One-Hot Encoding 的優勢是？',
    opts: ['A. One-Hot Encoding 能捕捉詞義相似性；Word Embedding 不行', 'B. Word Embedding 將詞映射至低維稠密向量，能捕捉語意相似性（語意相近的詞向量距離近）', 'C. Word Embedding 只能用於英文；One-Hot 支援任何語言', 'D. One-Hot Encoding 訓練速度比 Word Embedding 慢'],
    ans: 'B',
    exp: 'One-Hot Encoding 將每個詞表示為稀疏向量（維度等於詞彙量），無法反映詞間語義關係。Word2Vec（Skip-gram / CBOW）透過預測上下文詞訓練低維稠密向量，使語意相近的詞（如 "king"、"queen"）向量距離相近，並支援向量運算（King - Man + Woman ≈ Queen）。現代 LLM 使用上下文相關的動態 Embedding（如 BERT）。',
  },
];


// ════════════════════════════════════════════════════════
//  科目二 模擬試題
// ════════════════════════════════════════════════════════
const S2_QUESTIONS = [
  {
    subject: '科目二',
    q: 'Hadoop HDFS 預設將每個資料 Block 複製幾份以確保容錯？',
    opts: ['A. 1 份（不複製）', 'B. 2 份', 'C. 3 份', 'D. 5 份'],
    ans: 'C',
    exp: 'HDFS 預設將每個 Block（預設 128MB）複製 3 份，分散儲存於不同 DataNode（盡量跨機架），確保即使單一節點故障，資料仍可從其他副本存取。',
  },
  {
    subject: '科目二',
    q: 'MapReduce 中「Shuffle and Sort」階段的主要功能是？',
    opts: ['A. 將原始輸入資料切割分配給 Mapper', 'B. 將 Map 輸出的相同 Key 資料排序後送給同一 Reducer', 'C. 將最終結果寫入 HDFS', 'D. 監控各節點資源使用'],
    ans: 'B',
    exp: 'Shuffle and Sort 將各 Mapper 輸出的 Key-Value 對，按 Key 進行分組（Partitioning）和排序（Sorting），確保相同 Key 的所有 Value 被傳送到同一 Reducer 聚合。',
  },
  {
    subject: '科目二',
    q: '根據 CAP 定理，Apache Cassandra 屬於哪種類型？',
    opts: ['A. CA 系統', 'B. CP 系統（一致性 + 分區容錯）', 'C. AP 系統（可用性 + 分區容錯）', 'D. CAP 三者均滿足'],
    ans: 'C',
    exp: 'Cassandra 設計為高可用性優先，採用最終一致性（Eventual Consistency），屬於 AP 系統。寫入時使用可調一致性（Tunable Consistency），允許部分節點不同步，確保網路分區時仍可讀寫。',
  },
  {
    subject: '科目二',
    q: 'Apache Spark 「惰性求值（Lazy Evaluation）」的意義是？',
    opts: ['A. Spark 立即計算每個操作結果', 'B. Transformation 不立即執行，遇到 Action 才觸發計算', 'C. Spark 自動延遲低優先權任務', 'D. 資料讀取等待硬碟 I/O 完成後才繼續'],
    ans: 'B',
    exp: 'Spark 的惰性求值讓 Transformation（如 map、filter、join）只建立執行計劃（DAG），不立即執行。只有當 Action（如 count、collect、save）被呼叫時，才真正執行整個計算流水線並最佳化執行計劃。',
  },
  {
    subject: '科目二',
    q: '資料正規化中「Min-Max Normalization」的正確公式是？',
    opts: ['A. x\' = (x − mean) / std', 'B. x\' = (x − min) / (max − min)', 'C. x\' = x / max', 'D. x\' = log(x + 1)'],
    ans: 'B',
    exp: 'Min-Max Normalization 公式：x\' = (x − min) / (max − min)，將所有值線性縮放至 [0, 1]。適合已知範圍的特徵，但對異常值敏感。Z-score Standardization（選項A）縮放至均值0、標準差1，對異常值更穩健。',
  },
  {
    subject: '科目二',
    q: 'Lambda 架構中「速度層（Speed Layer）」的主要職責是？',
    opts: ['A. 儲存所有歷史原始資料供批次重計算', 'B. 處理即時串流資料，提供低延遲的即時視圖', 'C. 合併批次層和速度層的結果供查詢', 'D. 管理資料存取權限和加密'],
    ans: 'B',
    exp: 'Lambda 三層架構：批次層（處理全量歷史資料，高延遲）、速度層（處理最新串流資料，低延遲，填補批次層延遲缺口）、服務層（合併兩層結果回應查詢）。速度層負責提供近即時視圖。',
  },
  {
    subject: '科目二',
    q: 'Kafka 中「Consumer Group」機制主要用於？',
    opts: ['A. 確保所有消費者收到每一條訊息', 'B. 讓多個消費者並行消費不同 Partition，實現水平擴展', 'C. 自動壓縮過期訊息節省儲存空間', 'D. 對訊息進行加密傳輸'],
    ans: 'B',
    exp: 'Consumer Group 允許多個 Consumer 實例分攤一個 Topic 的不同 Partition，實現平行消費與水平擴展。同一 Group 內每個 Partition 只由一個 Consumer 消費；不同 Group 間各自獨立消費全量訊息。',
  },
  {
    subject: '科目二',
    q: 'K-means 演算法「收斂」是指什麼狀態？',
    opts: ['A. K 值達到資料點總數時停止', 'B. 群心位置不再移動，資料點分配穩定', 'C. 所有群的樣本數量相等', 'D. 組內距離平方和（WCSS）等於零'],
    ans: 'B',
    exp: 'K-means 迭代：分配每個點到最近群心 → 重新計算群心 → 重複。當群心位置不再改變（或改變量小於閾值 ε）時收斂停止。WCSS=0 意味著 K=N（每點一群），實際上無意義。',
  },
  {
    subject: '科目二',
    q: 'Google BigQuery 相較於傳統 Hadoop 叢集最大優勢是？',
    opts: ['A. 支援更多程式語言 SDK', 'B. Serverless 架構，無需管理叢集，依查詢量計費', 'C. 資料需先上傳至本地端才能查詢', 'D. 只支援 CSV 格式'],
    ans: 'B',
    exp: 'BigQuery 是 Serverless 全代管資料倉儲，不需管理任何伺服器；使用欄式儲存（Columnar Storage）和 Dremel 分散式查詢引擎，在 PB 級資料上可秒速完成複雜 SQL 查詢，費用按掃描資料量計算。',
  },
  {
    subject: '科目二',
    q: 'PCA（主成分分析）的主要應用場景是？',
    opts: ['A. 提升模型預測準確率', 'B. 降低資料維度，減少雜訊並加速模型訓練', 'C. 將離散類別變數轉換為連續數值', 'D. 填補資料集中的缺失值'],
    ans: 'B',
    exp: 'PCA 透過線性變換，將原始高維特徵投影到保留最大變異量的低維正交主成分空間，達到降維目的。應用：減少特徵數降低計算量、去除多共線性（Multicollinearity）、資料視覺化（降至 2D/3D）。',
  },
  {
    subject: '科目二',
    q: '關聯規則中「Lift（提升度）> 1」表示什麼？',
    opts: ['A. 購買項目 A 的交易佔所有交易的比例超過 1%', 'B. 購買 A 後又購買 B 的機率超過 1%', 'C. A 與 B 呈正相關，購買 A 會增加購買 B 的機率', 'D. 包含 A 和 B 的交易超過 1 筆'],
    ans: 'C',
    exp: 'Lift = Confidence(A→B) / P(B) = P(A∩B) / (P(A)×P(B))。Lift>1 表示 A 與 B 正相關（購買 A 增加購買 B 的機率）；Lift=1 獨立；Lift<1 負相關。Lift 是判斷關聯規則是否有實際意義的關鍵指標。',
  },
  {
    subject: '科目二',
    q: '資料湖（Data Lake）與資料倉儲（Data Warehouse）最主要的差異是？',
    opts: ['A. 資料湖只支援 SQL；資料倉儲支援所有語言', 'B. 資料湖以原始格式儲存多種資料；資料倉儲儲存 ETL 後的結構化資料', 'C. 資料倉儲儲存成本更低', 'D. 資料湖只能本地部署；資料倉儲必須雲端'],
    ans: 'B',
    exp: '資料湖以原始格式儲存結構化/半結構化/非結構化資料，Schema on Read，適合資料科學探索。資料倉儲採 Schema on Write，資料需先 ETL 清洗為固定結構，適合 BI 報表和標準化查詢。',
  },
  {
    subject: '科目二',
    q: 'HDFS NameNode 單點故障（SPOF）的最佳解決方案是？',
    opts: ['A. 增加每個 Block 的複製數量', 'B. 設置 NameNode HA 架構（Active/Standby）搭配 ZooKeeper 自動切換', 'C. 使用更高規格伺服器替換 NameNode', 'D. 減少 DataNode 數量'],
    ans: 'B',
    exp: 'Hadoop HA 架構使用兩個 NameNode（Active/Standby），透過 ZooKeeper 監控 Active NameNode 狀態，故障時自動切換（Failover）到 Standby，解決傳統單 NameNode 的單點故障問題。',
  },
  {
    subject: '科目二',
    q: '串流處理中「水印（Watermark）」機制主要解決什麼問題？',
    opts: ['A. 加密串流資料防止洩漏', 'B. 處理事件時間亂序到達的問題', 'C. 控制 Kafka Consumer 讀取速率', 'D. 壓縮串流資料降低網路傳輸量'],
    ans: 'B',
    exp: '在事件時間（Event Time）串流處理中，因網路延遲等因素，事件可能亂序到達。Watermark 定義系統願意等待遲到事件的最長時間閾值，讓視窗在 Watermark 時間點觸發計算，平衡完整性與延遲。',
  },
  {
    subject: '科目二',
    q: 'A/B 測試中，p-value < 0.05 代表什麼意義？',
    opts: ['A. 實驗組效果比對照組提升了 5%', 'B. 在虛無假設為真時觀測到此結果的機率低於 5%，可拒絕虛無假設', 'C. 實驗需要再收集 5% 更多資料', 'D. 實驗的信心水準為 5%'],
    ans: 'B',
    exp: 'p-value 是在虛無假設（H₀：兩組無差異）為真時，觀測到現有或更極端結果的機率。p<0.05 表示結果在統計上顯著（信心水準 95%），可拒絕虛無假設。注意：統計顯著≠業務上有實質意義。',
  },
  {
    subject: '科目二',
    q: 'Apache Hive 與 HBase 的主要使用場景差異是？',
    opts: ['A. Hive 適合即時隨機讀寫；HBase 適合批次分析', 'B. Hive 適合批次 SQL 分析查詢；HBase 適合低延遲隨機讀寫', 'C. 兩者功能完全相同', 'D. Hive 基於記憶體；HBase 基於磁碟'],
    ans: 'B',
    exp: 'Hive 將 HiveQL 轉換為 MapReduce/Tez 執行，適合大量資料批次查詢（如每日報表），延遲秒至分鐘級。HBase 是基於 HDFS 的 NoSQL 列式資料庫，支援毫秒級隨機讀寫，適合需要即時查詢的應用（如用戶資料、訊息系統）。',
  },
  {
    subject: '科目二',
    q: 'Spark DataFrame 相較於 RDD 的主要優點是？',
    opts: ['A. DataFrame 支援更多程式語言', 'B. DataFrame 有 Schema 定義，可被 Catalyst 最佳化引擎優化，通常效能更高', 'C. RDD 已被棄用不可使用', 'D. DataFrame 不支援容錯機制'],
    ans: 'B',
    exp: 'DataFrame 有結構化 Schema，Spark 的 Catalyst 最佳化器可分析查詢計劃並自動最佳化（如謂詞下推、列裁剪），通常比 RDD 效能更好且程式碼更簡潔。DataFrame 底層仍基於 RDD 實作。',
  },
  {
    subject: '科目二',
    q: 'Kafka Partition 數量與消費者數量的最佳實踐關係是？',
    opts: ['A. Consumer 數量應等於 Topic 總數', 'B. 同一 Consumer Group 中 Consumer 數量不應超過 Partition 數量', 'C. Partition 越少吞吐量越高', 'D. 每個 Partition 必須有獨立的 Broker'],
    ans: 'B',
    exp: '在同一 Consumer Group 中，每個 Partition 最多由一個 Consumer 消費。若 Consumer 數量 > Partition 數量，多餘的 Consumer 閒置不工作。因此增加 Partition 數量可提升平行度，但也增加管理複雜度。',
  },
  {
    subject: '科目二',
    q: '「資料倉儲星型綱要（Star Schema）」與「雪花綱要（Snowflake Schema）」最主要的差異是？',
    opts: ['A. 星型綱要只能儲存財務資料', 'B. 星型綱要維度表不正規化（查詢快）；雪花綱要維度表正規化（節省空間）', 'C. 雪花綱要查詢效能優於星型綱要', 'D. 星型綱要不支援多個事實表'],
    ans: 'B',
    exp: '星型綱要：事實表（Fact Table）直接連接非正規化的維度表（Dimension Table），Join 少、查詢快，但有重複資料。雪花綱要：維度表進一步正規化拆分，節省儲存但 Join 多、查詢較慢。BI 實務常用星型。',
  },
  {
    subject: '科目二',
    q: '「ACID」事務特性中「原子性（Atomicity）」的意義是？',
    opts: ['A. 事務執行速度快如原子', 'B. 事務中所有操作要麼全部成功，要麼全部回滾，不存在部分完成', 'C. 資料庫同時只允許一個事務執行', 'D. 每個操作不可分割地對應一個資料庫行'],
    ans: 'B',
    exp: 'ACID 四特性：Atomicity（原子性：全成功或全回滾）、Consistency（一致性：事務前後符合業務規則）、Isolation（隔離性：事務間互不干擾）、Durability（持久性：提交後資料永久保存）。這是傳統 RDBMS 的核心保證。',
  },
  {
    subject: '科目二',
    q: '隨機森林（Random Forest）相較於單一決策樹的優點是？',
    opts: ['A. 訓練速度更快', 'B. 透過集成多棵決策樹並取多數投票，降低過擬合並提升泛化能力', 'C. 模型結構更容易解釋', 'D. 只需更少的訓練資料'],
    ans: 'B',
    exp: '隨機森林是 Bagging 集成方法：隨機抽取樣本（Bootstrap）和特徵子集，訓練多棵決策樹，最終取多數投票（分類）或平均（迴歸）。比單棵決策樹更不容易過擬合，對雜訊更穩健，但可解釋性較差。',
  },
  {
    subject: '科目二',
    q: '時間序列分析中，「季節性（Seasonality）」成分指的是？',
    opts: ['A. 長期單方向的趨勢變化', 'B. 固定週期重複出現的規律波動（如每年冬季銷售高峰）', 'C. 資料中無法預測的隨機雜訊', 'D. 外部事件造成的一次性衝擊'],
    ans: 'B',
    exp: '時間序列分解通常包含：趨勢（Trend，長期方向）、季節性（Seasonality，固定週期波動）、循環（Cycle，不固定長週期）、殘差（Residual，隨機雜訊）。識別季節性對銷售預測、電力負載預測很重要。',
  },
  {
    subject: '科目二',
    q: '「Apache Airflow」在資料工程中的主要用途是？',
    opts: ['A. 即時串流資料處理', 'B. 以 DAG 定義和排程管理資料管線（Data Pipeline）的工作流程', 'C. 分散式儲存大型資料集', 'D. 提供互動式資料查詢介面'],
    ans: 'B',
    exp: 'Airflow 以 Python 程式碼定義 DAG（有向無環圖），描述任務依賴關係並排程執行（如每日 ETL）。支援重試機制、監控儀表板、各種 Operator（Spark、SQL、HTTP 等），是現代資料工程最常用的工作流管理工具。',
  },
  {
    subject: '科目二',
    q: '「Delta Lake」相較於傳統資料湖（Data Lake）的核心改進是？',
    opts: ['A. 支援更多雲端平台', 'B. 在資料湖上支援 ACID 事務、時間旅行（Time Travel）和 Schema 演進', 'C. 查詢速度比傳統資料湖慢但更準確', 'D. 只支援結構化資料'],
    ans: 'B',
    exp: 'Delta Lake 在 Parquet 格式上加入事務日誌（Transaction Log），支援：ACID 事務（解決並發寫入問題）、Time Travel（可查詢歷史版本）、Schema Enforcement（防止壞資料進入）、Upsert/Delete（GDPR 合規）。',
  },
  {
    subject: '科目二',
    q: '資料品質的「完整性（Completeness）」維度指的是？',
    opts: ['A. 資料欄位定義清楚且有文件記錄', 'B. 資料集中缺失值（NULL/空值）的比例低，資料記錄齊全', 'C. 資料符合業務規則與格式規範', 'D. 不同系統間相同實體的資料一致'],
    ans: 'B',
    exp: '資料品質常見六維度：完整性（Completeness，無缺失）、準確性（Accuracy，資料正確）、一致性（Consistency，跨系統一致）、時效性（Timeliness，資料最新）、唯一性（Uniqueness，無重複）、有效性（Validity，符合規則）。',
  },
  {
    subject: '科目二',
    q: 'AWS Glue 在大數據架構中主要扮演什麼角色？',
    opts: ['A. 即時串流資料擷取服務', 'B. Serverless ETL 服務，自動爬取 Schema 並轉換資料格式', 'C. NoSQL 鍵值資料庫', 'D. 機器學習模型訓練平台'],
    ans: 'B',
    exp: 'AWS Glue 是全代管 Serverless ETL 服務：Glue Crawler 自動發現資料來源並推斷 Schema 存入 Glue Data Catalog；Glue ETL Job 以 PySpark/Scala 執行資料轉換，無需管理伺服器，常用於 S3 資料湖的資料整合。',
  },
  {
    subject: '科目二',
    q: '「列式儲存（Columnar Storage）」格式（如 Parquet）在 OLAP 查詢中的優勢是？',
    opts: ['A. 插入和更新速度比列式儲存快', 'B. 只讀取查詢所需的欄位，大幅減少 I/O，且同一欄位資料壓縮率高', 'C. 支援更多的資料類型', 'D. 適合高並發的交易型查詢（OLTP）'],
    ans: 'B',
    exp: '列式儲存將相同欄位的資料連續儲存，OLAP 查詢通常只需少數欄位（如 SELECT avg(price)），可跳過無關欄位，I/O 大幅減少。同欄位資料值域相近，壓縮率高（如 RLE、Dictionary Encoding），BigQuery、Redshift 均採用此方式。',
  },
  {
    subject: '科目二',
    q: '「資料血緣（Data Lineage）」在資料治理中的主要價值是？',
    opts: ['A. 追蹤資料從來源到最終使用的完整流向，便於除錯和合規審計', 'B. 自動清洗資料中的錯誤值', 'C. 加速資料查詢效能', 'D. 管理資料存取的帳號權限'],
    ans: 'A',
    exp: '資料血緣（Data Lineage）記錄資料從原始來源（如感測器、資料庫）經過各 ETL 轉換至最終報表的完整路徑。當資料出現問題時可快速追溯根因；也滿足 GDPR「被遺忘權」和 BCBS 239（金融業資料風險）等合規要求。',
  },
  {
    subject: '科目二',
    q: '「Exactly-Once 語意」在串流處理中的意義是？',
    opts: ['A. 每條訊息至少被處理一次，允許重複', 'B. 每條訊息恰好被處理一次，不多不少，保證結果精確', 'C. 訊息只被處理一次後立即刪除', 'D. 系統每秒精確處理一條訊息'],
    ans: 'B',
    exp: '串流處理的三種語意：At-Most-Once（最多一次，可能遺失）、At-Least-Once（至少一次，可能重複）、Exactly-Once（恰好一次，最強保證但實作複雜）。Apache Flink 和 Kafka Transactions 支援 Exactly-Once，適用於金融交易等精確性要求高的場景。',
  },
  {
    subject: '科目二',
    q: '迴歸評估中「MAE（平均絕對誤差）」相對於「MSE（均方誤差）」的特性是？',
    opts: ['A. MAE 對異常值更敏感，MSE 較不敏感', 'B. MAE 線性懲罰誤差對異常值較不敏感；MSE 平方懲罰使大誤差權重更高，對異常值敏感', 'C. MAE 和 MSE 計算結果完全相同', 'D. MAE 只用於分類問題；MSE 只用於迴歸'],
    ans: 'B',
    exp: 'MAE = 誤差絕對值的平均，每個誤差線性懲罰，對異常值（Outlier）較穩健，單位與原始資料相同易解釋。MSE = 誤差平方的平均，大誤差被放大懲罰，對異常值敏感，適合梯度下降最佳化。RMSE = √MSE，與原始資料同單位，兼顧 MSE 的最佳化優點與可解釋性。',
  },
  {
    subject: '科目二',
    q: 'DBSCAN 聚類演算法相較於 K-means 最主要的優勢是？',
    opts: ['A. 計算速度更快，適合即時處理', 'B. 可自動發現任意形狀群集且識別雜訊點，不需預先指定群數 K', 'C. 對高維度資料效果更好', 'D. 記憶體使用量更少'],
    ans: 'B',
    exp: 'DBSCAN（Density-Based Spatial Clustering of Applications with Noise）以ε鄰域半徑和 MinPts 定義核心點、邊界點和雜訊點（Noise）。優點：無需指定 K 值、可發現任意形狀群集（非球形）、自動識別異常值。K-means 假設球形群集且需指定 K，對非凸形狀效果差。DBSCAN 缺點是對ε和 MinPts 參數敏感。',
  },
  {
    subject: '科目二',
    q: '大數據儲存格式中「Parquet」與「Avro」的主要使用場景差異是？',
    opts: ['A. Parquet 適合串流傳輸；Avro 適合批次分析', 'B. Parquet 列式儲存適合 OLAP 分析查詢；Avro 行式儲存支援 Schema 演進，適合串流傳輸與序列化', 'C. 兩者完全相同都是列式儲存', 'D. Parquet 是文字格式；Avro 是二進位格式'],
    ans: 'B',
    exp: 'Parquet：列式儲存（Columnar）格式，壓縮率高，適合 OLAP 查詢（Spark、BigQuery 按欄讀取）。Avro：行式（Row-based）二進位格式，支援 Schema Evolution（Schema 向前/向後相容），適合 Kafka 訊息序列化和 Hadoop ETL 資料交換。常見組合：Kafka 傳輸用 Avro，儲存至資料湖後轉存為 Parquet 進行分析。',
  },
  {
    subject: '科目二',
    q: 'Hadoop YARN 中「ResourceManager」的主要職責是？',
    opts: ['A. 儲存 HDFS 所有 Block 的位置元資料', 'B. 管理叢集全域資源（CPU、記憶體），為各應用程式的 ApplicationMaster 分配容器', 'C. 在每個節點執行具體的 Map 和 Reduce 任務', 'D. 協調多個 NameNode 間的資料同步'],
    ans: 'B',
    exp: 'YARN（Yet Another Resource Negotiator）三大元件：ResourceManager（RM）—— 全域資源管理和作業排程；NodeManager（NM）—— 管理單一節點資源，執行 Container；ApplicationMaster（AM）—— 每個應用程式專屬，向 RM 申請資源並協調任務執行。RM 是叢集的中央資源仲裁者。',
  },
  {
    subject: '科目二',
    q: 'Kafka 中「Offset」的作用是？',
    opts: ['A. 記錄每個 Producer 的訊息寫入速率', 'B. 標記消費者在 Partition 中的讀取位置，確保重啟後可從上次位置繼續消費', 'C. 控制 Broker 之間 Leader/Follower 的資料同步進度', 'D. 設定 Topic 訊息的最長保留時間'],
    ans: 'B',
    exp: 'Kafka 每條訊息在 Partition 中有唯一遞增的 Offset（偏移量）。Consumer Group 透過提交（Commit）Offset 記錄已消費位置，重啟後從上次 Commit 的 Offset 繼續，避免重複消費或遺漏。Offset 儲存在 Kafka 內建 Topic（__consumer_offsets）中，是 Kafka 實現消費進度追蹤的核心機制。',
  },
  {
    subject: '科目二',
    q: 'Apache Flink 相較於 Spark Structured Streaming 的主要技術特點是？',
    opts: ['A. Flink 僅支援批次處理，不支援串流', 'B. Flink 是原生串流引擎（毫秒延遲），原生支援 Exactly-Once 和事件時間處理；Spark 採微批次架構延遲略高', 'C. Spark Streaming 比 Flink 延遲更低', 'D. Flink 不支援 Exactly-Once 語意'],
    ans: 'B',
    exp: 'Flink 是 Streaming-first 架構，以事件逐條處理（True Streaming），透過 Checkpoint 機制實現 Exactly-Once，延遲可達毫秒級。Spark Structured Streaming 採微批次（Micro-batch）架構，延遲通常秒級。Flink 在金融即時風控、IoT 即時分析等低延遲場景更佔優勢。兩者都支援批流一體。',
  },
  {
    subject: '科目二',
    q: 'Kappa 架構相較於 Lambda 架構的核心改進是？',
    opts: ['A. Kappa 新增了歷史批次層提升計算精度', 'B. Kappa 移除批次層，統一以串流處理引擎處理即時和歷史資料，降低架構複雜度', 'C. Kappa 在每個節點增加本地快取', 'D. Kappa 適合非結構化資料，Lambda 適合結構化資料'],
    ans: 'B',
    exp: 'Lambda 架構維護批次層和速度層兩套系統（程式碼重複、維運複雜）。Kappa 架構（Jay Kreps 提出）移除批次層，歷史資料重算也透過重新消費串流（如 Kafka 保留完整訊息）完成，統一串流引擎處理所有資料。適合 Kafka + Flink/Spark Streaming 的現代串流優先架構。',
  },
  {
    subject: '科目二',
    q: '現代雲端資料倉儲廣泛採用「ELT」而非傳統「ETL」的主要原因是？',
    opts: ['A. ELT 先轉換再上傳，減少雲端儲存費用', 'B. ELT 先載入原始資料至雲端倉儲，再利用倉儲強大算力彈性轉換，支援多樣化分析需求', 'C. ELT 不需要任何資料轉換步驟', 'D. ELT 只適用於非結構化資料'],
    ans: 'B',
    exp: 'ETL：先在中間層轉換後再載入，規則固定難以應對多變需求。ELT（Extract-Load-Transform）：先載入原始資料至雲端倉儲（如 BigQuery、Snowflake），再利用 SQL 在倉儲內轉換。雲端倉儲算力強大可按需計費，ELT 保留原始資料靈活性高，是現代資料棧（dbt + 雲端倉儲）的主流模式。',
  },
  {
    subject: '科目二',
    q: '若需儲存社群網路的「用戶關係圖」並高效查詢「朋友的朋友」，最適合的資料庫類型是？',
    opts: ['A. 鍵值資料庫（Key-Value Store）如 Redis', 'B. 文件資料庫（Document Store）如 MongoDB', 'C. 圖形資料庫（Graph Database）如 Neo4j', 'D. 列族資料庫（Column-Family）如 Cassandra'],
    ans: 'C',
    exp: '圖形資料庫以節點（Node）和邊（Edge）儲存實體與關係，在多層關係遍歷（如「朋友的朋友的朋友」）查詢上比關聯式資料庫高出數量級效率（無需多層 JOIN）。Neo4j 是最主流的圖形資料庫，適合社群網路分析、知識圖譜、推薦系統、詐欺偵測（資金流向追蹤）。',
  },
  {
    subject: '科目二',
    q: '卡方檢定（Chi-Square Test of Independence）適用於哪種分析場景？',
    opts: ['A. 比較兩組連續數值的均值是否有顯著差異', 'B. 檢驗兩個類別變數之間是否存在統計關聯性', 'C. 預測連續目標變數的未來數值', 'D. 評估時間序列資料的週期性'],
    ans: 'B',
    exp: '卡方獨立性檢定比較觀測頻率與期望頻率，判斷兩個類別變數（如性別 vs 購買行為）是否相互獨立。p-value < 0.05 拒絕獨立假設，即兩變數有統計關聯。t-test 比較兩組連續均值差異；ANOVA 比較多組；線性迴歸預測連續值。',
  },
  {
    subject: '科目二',
    q: '「特徵庫（Feature Store）」在 MLOps 的核心價值是？',
    opts: ['A. 儲存模型訓練完成後的權重文件', 'B. 集中管理並共享特徵計算邏輯，確保訓練/推論使用一致特徵，避免訓練-服務偏差', 'C. 自動執行特徵工程和特徵選擇', 'D. 提供特徵重要性的可解釋分析'],
    ans: 'B',
    exp: '特徵庫（Feature Store）解決 Training-Serving Skew（訓練時和推論時特徵計算不一致導致效能下降）。功能：特徵共享（不同團隊重用）、版本控制、Point-in-time Correct Joins（訓練時使用歷史正確特徵值）、線上/離線服務。代表工具：Feast、Tecton、Databricks Feature Store。',
  },
  {
    subject: '科目二',
    q: 'Apache Sqoop 在 Hadoop 生態系的主要功能是？',
    opts: ['A. 即時串流資料的擷取與處理', 'B. 在關聯式資料庫（RDBMS）與 HDFS/Hive 之間批次匯入/匯出資料', 'C. 分散式訊息佇列，解耦生產者和消費者', 'D. 工作流排程與資料管線監控'],
    ans: 'B',
    exp: 'Sqoop（SQL-to-Hadoop）是批次資料遷移工具：sqoop import 從 MySQL/Oracle/SQL Server 等 RDBMS 匯入資料至 HDFS/Hive/HBase；sqoop export 將 Hadoop 處理結果寫回 RDBMS。底層使用 MapReduce 平行傳輸，是傳統 ETL 管線中 RDBMS 與 Hadoop 橋接的標準工具。',
  },
  {
    subject: '科目二',
    q: '大數據系統中「資料分區（Partitioning）」的主要目的是？',
    opts: ['A. 增加資料備份副本數量提高容錯性', 'B. 將資料按規則分割為子集，提升查詢效能（分區裁剪）和平行處理效率', 'C. 加密資料分段防止未授權存取', 'D. 壓縮資料節省儲存空間'],
    ans: 'B',
    exp: '常見分區策略：Range（依範圍，如日期分區）、Hash（依 Key 雜湊均勻分散）、List（依固定值清單）。例如 Hive/Parquet 按日期分區後，查詢特定日期只掃描對應分區（Partition Pruning），大幅減少 I/O 掃描量。Kafka 的 Partition 也實現平行消費和水平擴展。',
  },
  {
    subject: '科目二',
    q: '識別資料集中「異常值（Outlier）」最常用的統計方法是？',
    opts: ['A. One-Hot Encoding 後比對向量距離', 'B. IQR 法：低於 Q1−1.5×IQR 或高於 Q3+1.5×IQR 的值視為異常值', 'C. Min-Max Normalization 後超過 1 的值視為異常', 'D. 計算眾數（Mode），與眾數差異大的視為異常'],
    ans: 'B',
    exp: 'IQR（四分位距）= Q3（75th percentile）− Q1（25th percentile）。Tukey 圍欄法：低於 Q1−1.5×IQR 或高於 Q3+1.5×IQR 的值為異常值，對非常態分佈較穩健。另一方法：Z-score 法（|z| > 3 視為異常），適合常態分佈資料。兩者常配合 Box Plot（箱型圖）視覺化使用。',
  },
  {
    subject: '科目二',
    q: '梯度提升（Gradient Boosting）與隨機森林（Random Forest）的核心差異是？',
    opts: ['A. 兩者完全相同，只是名稱不同', 'B. 隨機森林並行訓練獨立決策樹（Bagging）；梯度提升串行訓練，每棵樹修正前一棵的殘差（Boosting）', 'C. 梯度提升只能用於迴歸；隨機森林只能用於分類', 'D. 隨機森林對異常值不敏感；梯度提升完全不受異常值影響'],
    ans: 'B',
    exp: 'Bagging（如隨機森林）：對資料有放回抽樣，並行訓練多棵獨立決策樹，取投票/平均，降低變異（Variance）。Boosting（如 XGBoost、LightGBM、AdaBoost）：串行訓練，每棵樹專注修正前棵的錯誤（殘差），降低偏差（Bias）。Boosting 通常精度更高但更易過擬合；Random Forest 更穩健且訓練可平行化。',
  },
  {
    subject: '科目二',
    q: 'XGBoost 相較於傳統 GBDT 的主要改進是？',
    opts: ['A. XGBoost 使用神經網路替代決策樹', 'B. 加入正則化項（L1/L2）防止過擬合、支援平行計算和稀疏資料，以及近似分裂算法提升效能', 'C. XGBoost 不需要調整超參數', 'D. XGBoost 只能處理結構化資料'],
    ans: 'B',
    exp: 'XGBoost 對傳統 GBDT 的改進：①目標函數加入 L1/L2 正則化，控制模型複雜度；②二階泰勒展開精確計算分裂增益；③稀疏感知算法（Sparsity-aware）處理缺失值；④支援列採樣（Column Subsampling）；⑤並行計算分裂點。在表格資料競賽中長期稱霸（Kaggle），LightGBM 以直方圖算法進一步提速。',
  },
  {
    subject: '科目二',
    q: '「支撐向量機（SVM）」中「核函數（Kernel Function）」的作用是？',
    opts: ['A. 計算每個支撐向量的距離', 'B. 將資料隱式映射至高維空間，使線性不可分的資料可以被線性超平面分離', 'C. 決定最大化邊界的懲罰係數', 'D. 過濾訓練資料中的雜訊點'],
    ans: 'B',
    exp: '核技巧（Kernel Trick）：透過核函數 K(x, x\') = φ(x)·φ(x\') 隱式計算高維映射後的內積，無需顯式計算高維向量。常見核：線性核（Linear）、多項式核（Polynomial）、RBF 高斯核（Radial Basis Function，最常用）、Sigmoid 核。RBF 核適合非線性邊界，超參數 C（懲罰）和 γ（RBF 寬度）需調優。',
  },
  {
    subject: '科目二',
    q: '「Precision-Recall 曲線」相較於「ROC 曲線」在什麼情況下更適合評估模型？',
    opts: ['A. 當資料集完全平衡時', 'B. 當資料集嚴重不平衡（正例極少），且更關注正例的識別精確度時', 'C. 當需要比較多個不同演算法時', 'D. 當模型輸出為多分類結果時'],
    ans: 'B',
    exp: 'ROC 曲線使用 TPR 和 FPR，FPR 在負例多時仍可維持低值，容易高估不平衡資料集上的模型表現。PR 曲線（Precision vs Recall）直接反映正例識別品質，在嚴重不平衡資料（如詐欺偵測、疾病篩檢，正例僅 1%）時更能揭示模型的真實能力。AUPRC（PR 曲線下面積）是更適合的評估指標。',
  },
  {
    subject: '科目二',
    q: 'Apache Spark 中「快取（Cache）」與「持久化（Persist）」的差異是？',
    opts: ['A. 兩者完全相同，Cache 是 Persist 的別名（預設 MEMORY_ONLY）', 'B. Cache 儲存在磁碟；Persist 儲存在記憶體', 'C. Cache 只對 DataFrame 有效；Persist 對 RDD 有效', 'D. Cache 是永久性的；Persist 是臨時的'],
    ans: 'A',
    exp: 'cache() 是 persist(StorageLevel.MEMORY_ONLY) 的快捷方式，只將 RDD/DataFrame 儲存在記憶體中。persist() 支援多種儲存等級：MEMORY_ONLY、MEMORY_AND_DISK（記憶體不足時溢出磁碟）、DISK_ONLY、MEMORY_ONLY_SER（序列化後存記憶體）等。迭代計算中快取中間結果可避免重複計算，顯著提升效能。',
  },
  {
    subject: '科目二',
    q: '串流處理中「滾動視窗（Tumbling Window）」與「滑動視窗（Sliding Window）」的差異是？',
    opts: ['A. 滾動視窗視窗之間有重疊；滑動視窗不重疊', 'B. 滾動視窗固定大小且不重疊；滑動視窗按固定步長移動，視窗可重疊', 'C. 滾動視窗只能處理批次資料；滑動視窗只能處理即時資料', 'D. 兩者功能完全相同'],
    ans: 'B',
    exp: '視窗類型：滾動視窗（Tumbling Window，如每 5 分鐘統計一次）—— 固定大小、不重疊，每個事件只屬於一個視窗；滑動視窗（Sliding Window，如每分鐘計算過去 5 分鐘）—— 視窗可重疊，事件可屬於多個視窗；會話視窗（Session Window）—— 根據活動間隔動態調整大小。Spark Structured Streaming 和 Flink 均支援三種類型。',
  },
  {
    subject: '科目二',
    q: '「Hive 的分桶（Bucketing）」與「分區（Partitioning）」的差異是？',
    opts: ['A. 兩者完全相同，只是名稱不同', 'B. 分區按欄位值建立目錄層次；分桶對指定欄位雜湊至固定桶數，優化 JOIN 和採樣', 'C. 分桶用於小資料；分區用於大資料', 'D. 分桶是動態的；分區是靜態的'],
    ans: 'B',
    exp: '分區（Partitioning）：按欄位值（如 dt=2024-01-01）建立子目錄，查詢時跳過不相關分區（Partition Pruning），適合範圍查詢。分桶（Bucketing）：對指定欄位做 HASH % N，相同 Key 的資料落入相同桶，優化相同欄位的 JOIN（Bucket Map Join，避免全量 Shuffle）和均勻採樣。兩者可組合使用。',
  },
  {
    subject: '科目二',
    q: '「資料湖屋（Lakehouse）」架構解決了什麼問題？',
    opts: ['A. 讓資料湖支援更多的檔案格式', 'B. 在資料湖儲存上結合事務管理（ACID）和 BI 查詢效能，兼具資料湖靈活性和資料倉儲可靠性', 'C. 將多個資料倉儲統一為一個中央倉儲', 'D. 解決資料湖查詢速度過慢的問題'],
    ans: 'B',
    exp: 'Lakehouse 架構（Databricks 提出，Apache Iceberg / Delta Lake / Apache Hudi 實現）結合：資料湖的低成本儲存（物件儲存）+ 資料倉儲的 ACID 事務、Schema Enforcement、BI 查詢效能。解決了傳統雙層架構（資料湖+資料倉儲）的資料重複、同步延遲和維護成本問題。',
  },
  {
    subject: '科目二',
    q: 'NoSQL 中「Redis」最典型的應用場景是？',
    opts: ['A. 儲存大量歷史交易記錄進行分析', 'B. 快取（Cache）、Session 管理、即時排行榜、訊息發布/訂閱', 'C. 儲存複雜的圖形關係網路', 'D. 批次處理結構化報表資料'],
    ans: 'B',
    exp: 'Redis 是記憶體內鍵值資料庫（In-memory Key-Value Store），讀寫延遲低至微秒。典型場景：①快取（Cache Aside 模式）減少資料庫壓力；②Session 儲存（水平擴展的 Web 應用）；③計數器/排行榜（INCR、ZADD）；④訊息佇列（List Push/Pop）；⑤分散式鎖（SETNX）；⑥即時資料統計。',
  },
  {
    subject: '科目二',
    q: '「Apache Iceberg」相較於傳統 Hive 表的優勢是？',
    opts: ['A. 提供更快的串流處理能力', 'B. 支援 Schema 演進、隱藏分區、時間旅行和 ACID 事務，解決大規模資料湖的可靠性問題', 'C. 只支援 Parquet 一種格式', 'D. 比 Hive 使用更少的儲存空間'],
    ans: 'B',
    exp: 'Apache Iceberg 開放表格格式（Open Table Format）的核心功能：①Schema Evolution（新增/刪除欄位不需重寫資料）；②Hidden Partitioning（自動管理分區，無需使用者手動指定）；③Time Travel（透過 snapshot 查詢歷史版本）；④Row-level Operations（支援 UPDATE/DELETE，ACID 保證）。Netflix 和 Apple 的生產環境廣泛採用。',
  },
  {
    subject: '科目二',
    q: '資料管線中，「向量資料庫（Vector Database）」的主要用途是？',
    opts: ['A. 儲存模型訓練的梯度向量', 'B. 高效儲存和相似度搜尋高維度嵌入向量（Embedding），支援語意搜尋和 RAG', 'C. 加速矩陣計算提升 SQL 查詢效能', 'D. 儲存時間序列的多維度感測器資料'],
    ans: 'B',
    exp: '向量資料庫（如 Pinecone、Weaviate、Milvus、pgvector）專為高維度向量的 ANN（近似最近鄰）搜尋優化，使用 HNSW 或 IVF 索引結構。在 RAG 架構中，將文件轉換為 Embedding 向量儲存，查詢時找出語意最相似的文件作為 LLM 上下文。',
  },
  {
    subject: '科目二',
    q: 'Spark Streaming 接收 Kafka 資料時，「Direct API」相較於「Receiver API」的優勢是？',
    opts: ['A. Receiver API 設定更簡單', 'B. Direct API 直接從 Kafka Partition 讀取並自行管理 Offset，零資料遺失且避免重複，無需 WAL', 'C. Receiver API 支援更多資料來源', 'D. Direct API 只支援 Kafka 0.8 以下版本'],
    ans: 'B',
    exp: 'Receiver API 使用獨立的 Receiver 執行緒拉取資料並寫入 WAL（預寫日誌）防止遺失，有吞吐限制且 Kafka Partition 與 Spark Partition 不一一對應。Direct API（Kafka Direct）：Spark 直接從 Kafka Partition 拉取，RDD Partition 對應 Kafka Partition，自行管理 Offset（存於 Checkpointing），支援 Exactly-Once 且效能更高。',
  },
  {
    subject: '科目二',
    q: '「資料目錄（Data Catalog）」在現代資料治理中的核心功能是？',
    opts: ['A. 自動清洗資料集中的錯誤記錄', 'B. 集中管理資料資產的元資料（Metadata），讓使用者能探索、理解和信任資料', 'C. 加速 SQL 查詢的執行計劃生成', 'D. 將資料從多個來源自動同步至單一資料倉儲'],
    ans: 'B',
    exp: '資料目錄（如 Apache Atlas、Alation、Collibra、AWS Glue Data Catalog）管理：資料資產的技術元資料（Schema、欄位說明）、業務元資料（業務術語、擁有者）、操作元資料（資料血緣、使用頻率）。讓資料工程師、分析師快速發現（Data Discovery）可信的資料集，是資料民主化（Data Democratization）的基礎。',
  },
  {
    subject: '科目二',
    q: '「資料網格（Data Mesh）」架構的核心設計原則是？',
    opts: ['A. 將所有資料集中至中央資料平台由統一團隊管理', 'B. 以業務領域為單位，各領域團隊自治管理並發布資料產品，分散式治理替代集中式', 'C. 使用微服務架構取代單體資料倉儲', 'D. 讓每個應用系統直接讀取其他系統的生產資料庫'],
    ans: 'B',
    exp: 'Data Mesh（Zhamak Dehghani 提出）的四大原則：①領域導向所有權（Domain Ownership）—— 各業務領域擁有自己的資料；②資料即產品（Data as a Product）—— 資料需有 SLA 和文件；③自助式資料平台（Self-Serve Platform）；④聯邦計算治理（Federated Governance）。解決集中式資料湖團隊成為瓶頸的問題。',
  },
  {
    subject: '科目二',
    q: '「邏輯迴歸（Logistic Regression）」輸出值的意義是？',
    opts: ['A. 預測目標變數的連續數值', 'B. 透過 Sigmoid 函數將線性組合轉換為 0~1 的機率，代表屬於正類的機率', 'C. 輸出每個類別到超平面的距離分數', 'D. 直接輸出 0 或 1 的硬分類標籤'],
    ans: 'B',
    exp: '邏輯迴歸使用 Sigmoid 函數：P(y=1|x) = 1/(1+e^(-z))，將線性組合 z=w·x+b 映射至 [0,1] 機率空間，以 0.5 為預設閾值分類（可調整以平衡 Precision/Recall）。雖名為「迴歸」，實為二元分類演算法，可解釋性高，是信用評分、疾病預測等領域的常用基線模型。',
  },
  {
    subject: '科目二',
    q: '線性迴歸評估中「R²（決定係數）」的意義是？',
    opts: ['A. 預測值與真實值差的平均絕對值', 'B. 模型解釋目標變數總變異的比例，1 為完美擬合，0 等同直接用均值預測', 'C. 訓練集準確率的百分比', 'D. 殘差的均方根'],
    ans: 'B',
    exp: 'R²（決定係數）= 1 - SS_殘差/SS_總變異，反映模型解釋了多少目標變數的變異量。R²=1：完美擬合；R²=0：預測效果等同均值；R²<0：模型比均值更差。與 RMSE/MAE 互補使用：RMSE 反映絕對誤差大小，R² 反映相對解釋能力，是迴歸模型的核心評估指標之一。',
  },
  {
    subject: '科目二',
    q: 'Spark 中「廣播 JOIN（Broadcast Join）」的適用情境是？',
    opts: ['A. 兩個超大資料表進行 JOIN', 'B. 將小型資料表廣播至所有節點記憶體，大表在本地直接 JOIN，避免 Shuffle 的網路傳輸', 'C. 跨多個 Spark 叢集的分散式 JOIN', 'D. 僅支援 Key-Value 格式資料的 JOIN'],
    ans: 'B',
    exp: 'Broadcast Join（Map-side Join）將小表（通常 < 10MB，可調 spark.sql.autoBroadcastJoinThreshold）廣播複製到每個 Executor 節點記憶體，大表分區在本地完成 JOIN，完全避免 Shuffle。比 Sort-Merge Join（需雙方 Shuffle）效能顯著更高。可手動用 broadcast() 函數觸發，適合大表 JOIN 維度表的 Star Schema 查詢。',
  },
];
